### ISSUE TITLE
scope not defined when configuring workflow "Submit message / Go to page"

### ISSUE THREAD

**Issue by TheFogOfWar1** [umbraco/Umbraco.Forms.Issues#1001]
When the forms developer uses the button configure workflow and want's to edit the "Submit message / Go to page" workflow the scope is not defined. 

Reproduction
------------
The developer clicks on 
![image](https://user-images.githubusercontent.com/22054828/228826927-56e0e0e9-0904-4b56-8144-0ec7163769c2.png)

After that the developer clicks on the "Submit message / Go to page" workflow. One would expect that an overlay is opened. However the following error shows in the browser console: 

![image](https://user-images.githubusercontent.com/22054828/228827565-d2f959e5-834a-441b-bcc3-5989b3e70009.png)

![image](https://user-images.githubusercontent.com/22054828/228827800-b2ad08f4-8839-4a5d-99b3-8fca91aa4e74.png)

### Specifics
Version of umbraco v11.2.2
Version of umbraco forms v11.1.0
Browser: Edge/Chrome

**Comment by AndyButland** [comment]
Thanks for reporting, and yes, this was a regression issue in the last release.  We've already had [it brought to our attention](https://github.com/umbraco/Umbraco.Forms.Issues/issues/998) and it'll be fixed in the next release due out next Tuesday.

Meantime to workaround there's another route via the UI to this page, via clicking the "Submit message / Go to page" label directly.
