### ISSUE TITLE
Existing vulnerabilities reported on Sonatype 

### ISSUE THREAD

**Issue by collinsed-af** [umbraco/Umbraco.Forms.Issues#1006]
The following issues are reported on sonatype with details. If this issue has been addressed, the reports would need to be remedied so the CVE is no longer attached to them. Based on the date these were identified, they may have been addressed already. 
In our corporate environment we cannot use packages that have these issues. We are not able to deploy any version of UmbracoForms currently. 

[CVE-2021-33224] CWE-434: Unrestricted Upload of File with Dangerous Type
https://ossindex.sonatype.org/vulnerability/CVE-2021-33224?component-type=nuget&component-name=UmbracoForms&utm_source=proget&utm_medium=integration&utm_content=22.0.24.5

[CVE-2020-7685] CWE-1188
https://ossindex.sonatype.org/vulnerability/CVE-2020-7685?component-type=nuget&component-name=UmbracoForms&utm_source=proget&utm_medium=integration&utm_content=22.0.24.5

**Comment by AndyButland** [comment]
Hi - the first of these relates to a specific version, which has been resolved in later ones. There's a blog post [here ](https://umbraco.com/blog/security-advisory-20th-of-july-2021-patch-is-now-available/)which links through to the reporters blog and there to the CWE listed.

The second one really is describing a feature of the product, which does allow you to create an upload form field and allow upload of files.  Some specific extensions are permanently blocked, but otherwise it's in the control of the person setting up the form.

If you want to simply remove that piece of functionality you can customise the list of extensions blocked [via configuration](https://docs.umbraco.com/umbraco-forms/developer/configuration#disallowedfileuploadextensions), by [removing the "File Upload" filed type](https://docs.umbraco.com/umbraco-forms/developer/extending/adding-a-type#registering-the-class-with-umbraco-and-forms) from use in your installation.

**Comment by c9mb** [comment]
@AndyButland - Considering it's a 2020, does this CVE actually still apply to the current version?

https://cwe.mitre.org/data/definitions/1188.html

> The product initializes or sets a resource with a default that is intended to be changed by the administrator, but the default is not secure.

Allowing upload of all file-types would not appear to be the current default config.

**Comment by AndyButland** [comment]
That's correct @c9mb yes, the default for the file upload is to use a specified, empty list of file extensions, so you have to opt into the ones you want, or you can select all, which will accept all apart from those marked as always excluded in configuration.

![image](https://user-images.githubusercontent.com/1993459/231944377-e28a4ca8-a105-4052-98a1-77f7eb85c543.png)

**Comment by c9mb** [comment]
Exactly - The CVE listings are great for discovering issues, but typically silent on the fixes/updates that mitigate them.
To my knowledge, they don't just disappear, and even entries such as Log4J remain listed, despite being patched.

**Comment by collinsed-af** [comment]
@AndyButland, Thanks for the help on this! 
I believe you are correct about the issues will remain listed even though there is a remedy. The only solution in my case is for our staff to permanently mitigate them internally. 
I'm going to close this.
