### ISSUE TITLE
Add the ability to alert CMS users of Workflow failures

### ISSUE THREAD

**Issue by Attackmonkey** [umbraco/Umbraco.Forms.Issues#1042]
This has come up a few times with clients recently, and I think it's potentially a really useful feature.

You've added the ability to see an audit trail of the workflows and even re-run the workflows in case of an issue, which is super useful. One thing that's missing is the ability for workflows to alert someone if they fail. To give you an example, lets say you have a form with a workflow that posts to something like Salesforce. Occasionally this may fail because of a data issue, in which case a CMS user would go in, fix the data issue and re-run the workflow successfully.

Currently a user would have to log in, and scan through form entries looking for failed workflows. This can be onerous on high submission volume forms. What we were thinking was it should be possible to check a box to say "alert if workflow fails" on each workflow and if checked allow the user to enter an email address (possibly with a fallback to an email in the forms config in appSettings).

I'm thinking this should be per workflow rather than a global setting as you may only need it for specific workflows on certain forms, having it globally might result in too many emails.

The email sent could just say which workflow failed, on what form, and then have a deep link to the form entry in the CMS so that the user can click to see the entry and investigate/take appropriate action.

Another option would be to expose a workflow completed notification with a status of completed/failed that people could subscribe to and handle appropriately.

---
_This item has been added to our backlog AB#35615_

**Comment by AndyButland** [comment]
We do have a `WorkflowExecutionFailedNotification`, so I think - as per your last sentence - you could handle to implement this.  Looks like it exposes the workflow, and from there the form, as well as the exception details, so it seems that the information you would need is available.

**Comment by Attackmonkey** [comment]
Awesome! Didn't realise that was available, it looks like it should allow us to do what we want I think 😊

**Comment by digbyswift-joe** [comment]
We had a similar need, and the `WorkflowExecutionFailedNotification` works well. Ideally though, we would additionally like to be able to access the record of the form being submitted.

Our use case is sending an email to a group of CMS editor recipients when the workflow fails. I would want to be able to retrieve the record ID and details so we can send a friendly email, and also include a link to the record in the CMS so that the workflow can be retriggered.

The notification doesn't currently seem to expose the record. Do we know of any way I could achieve this?

**Comment by AndyButland** [comment]
I had a quick look - it does seem like we could/should include the record in this notification without any issues.  We'll have a look at including this for the next release.

**Comment by digbyswift-joe** [comment]
@AndyButland Thank you for the update - sounds really positive 👍 

While we are looking into plans to update this particular site to more recent versions, our Forms / CMS installation are still on v10.

Is this a change that could possibly be able to be made on those versions, or would it only be applied on v12 onwards?

**Comment by AndyButland** [comment]
I think we'd consider the feature to link directly to a given entry to be something for 12 only.  That was certainly the intetion. 
 That's the version people should be on to get access to new features, and means we can keep 10 stable without less risk of breaking something in introducing something new.

I'd be inclined to see the lack of access to the record data in the workflow notifications as an oversight though - i.e. something that should have been there all along and arguably you could say it is a "bug" that it's not.  So that would I'd be happy to include in a patch release of 10.

**Comment by digbyswift-joe** [comment]
@AndyButland That seems perfectly reasonable - and thanks for getting back to me so quickly. Will look forward to these releases...
