### ISSUE TITLE
Field size in Umbraco Forms

### ISSUE THREAD

**Issue by HenrikNSkaerbaek** [umbraco/Umbraco.Forms.Issues#1047]
The standard field size must be like v256

Reproduction
------------

Try creating a form with a hiddenfield that take the [@Url] as value and create a url with params that are really long.. longer than 256 I guess.

### Bug summary

When we have Hiddenfields in our Formulars and we get data that is longer than 256 (dont know the exat limit)
for example with [@Url] the query can get really long with all the parameters. And if one of the fields have data that are to long then the form entry isnt saved in umbraco !

### Specifics

Umbraco version 10.5.1
Umbraco Forms 10.4.0

### Steps to reproduce

Try creating a form with a hiddenfield that take the [@Url] as value and create a url with params that are really long.. longer than 256 I guess.

### Expected result

The entry save correctly in the database and shown in the backoffice form view.

### Actual result

I would like to be able to dont have that limitation on the form fields and the entry should be stored either way.. then the string must have been cut after the max length as a minimum of failure or the rest of the form entry is saved without that fieldinfo. The frontend get a success.

**Comment by AndyButland** [comment]
It's true that the hidden field provided by Forms out of the box is intended only for the hidden equivalent of the "short answer" field, which is limited to 255 characters.  If you need to store values longer than that, it's probably best to create a custom field type that sets the `DataType` to `FieldDataType.LongString`.  You could add this to your installation in addition to or instead of the existing one.

Documentation for creating a custom field type is found [here](https://docs.umbraco.com/umbraco-forms/v/10.latest-lts-2/developer/extending/adding-a-fieldtype).
