### ISSUE TITLE
Umbraco forms 12 Nuget package issue - missing files

### ISSUE THREAD

**Issue by thenexus00** [umbraco/Umbraco.Forms.Issues#1052]
No templates, no partial views and macro partial views installed.

Reproduction
------------

- Umbraco 12 install/ existing setup
- Nuget package manager in visual studio code
- Install Umbraco Forms 12
- Finish and build project
- Umbraco forms appears in admin and you can create forms
- Form picker insertion issue as while references macro view path it has not been installed
- No form or field partial views installed
- No templates or anything installed - Basically nothing front end facing

### Specifics

Literally anything front facing does not appear to be installed.

### Expected result

Expected partial views etc to be installed as with previous versions so forms can render on websites.

### Actual result
Forms can be made but can not be rendered

**Comment by AndyButland** [comment]
I'm not able to replicate the problem here.  With Umbraco 12 (and from 10+) the partial views are provided as part of a Razor Class Library, and hence you shouldn't expect to see them on disk.

Just to be sure I've just done the following and could render the form as expected:

```
dotnet new install Umbraco.Templates
dotnet new umbraco -n Test12
cd Test12
dotnet add package Umbraco.Forms
dotnet run
```

Then completed the installer, created a form, doc type with a form picker and content item - and could see the form rendering as expected.

**Comment by AndyButland** [comment]
Will close this one now given there's been no further discussion.  Please feel free to re-open though if you still experience the issue and ideally can replicate with something like the steps I've used above.
