### ISSUE TITLE
Umbraco Forms: 10.5.0-rc1 new issue with dropdown mandatory

### ISSUE THREAD

**Issue by troshan** [umbraco/Umbraco.Forms.Issues#1059]
Dropdown mandatory validation message not showing under validation summary 

Reproduction
------------

Install Umbraco Forms: 10.5.0-rc1
Create a Dropdown field EX: countries and add few items
Make it mandatory
Enable validation summary 

Now submit the form without selecting any items. 
Validation summary is not picking the error

### Bug summary

Dropdown mandatory validation message not showing under validation summary 
### Expected result

Dropdown mandatory error validation message should be visible at validation summary

### Actual result

Other error messages are showing but not showing drop-down field error message at validation summary

**Comment by AndyButland** [comment]
Thanks for the report.  It looks like this has been caused due to a change in the client library we use for validation... which comes from a PR from me to resolve #1053.

Fortunately it looks like someone has [stepped in a fixed the regression](https://github.com/haacked/aspnet-client-validation/pull/60) I caused with that update.

I can replicate the issue with 10.5.0-rc1, and if I update to what is now the latest version of aspnet-client-validation, can also see this resolves the issue.  So we'll reference the latest in the final release for 10.5 and 12.1.
