### ISSUE TITLE
Feature: Toggle buttons fields and/or multi-step forms would also be very cool.

### ISSUE THREAD

**Issue by Marco-Rinia** [umbraco/Umbraco.Forms.Issues#1090]
Toggle buttons fields available and/or multi-step forms would also be very useful.

**Comment by AndyButland** [comment]
Multi-step forms already exist in the product, and toggle buttons as I understand are really just checkboxes with appropriate CSS, so that should be something for an implementor to apply.  Whilst we could ship a toggle field in addition to the existing checkbox, as it's not a native-browser implementation, we'd have to make decisions on how it would look, which likely isn't appropriate for a general purpose package.
