### ISSUE TITLE
HTML file upload causes on-submit redirect to fail (v10)

### ISSUE THREAD

**Issue by nathangchay** [umbraco/Umbraco.Forms.Issues#1095]
Uploading a HTML file to a file upload property on a form (with all file types allowed) causes submission of the form to refresh the page instead of redirecting to the page specified in the workflow. The form still submits successfully. 

Reproduction
------------

### Specifics

* Umbraco 10.6.1
* Umbraco.Forms 10.5.0 and 10.5.1
* Google Chrome 116.0.5845.97 (Not tested in other browsers)

### Steps to reproduce

1. Create a new v10.6.1 site.
2. Install Umbraco.Forms 10.5.1.
3. Create a new form with a file upload property that allows all file types.
4. Create a new document type with an RTE property and a template that renders it.
5. Create a content page for the form and a success page.
6. Add the success page to the form's workflow.
7. Compare the results of uploading an HTML file and uploading a different file type.

### Expected result

After form submission, the user is redirected to the success page specified in the form's workflow.

### Actual result

The page refreshes and the user is not redirected. There are no error messages or warnings in the logs, apart from this "ping" that appears in the console - not sure if this actually has anything to do with the issue.
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/46760843/d53c7757-7fa1-428e-bc7b-ca4d66e22081)

**Comment by AndyButland** [comment]
I'm afraid I've not been able to replicate this issue.  I'd appreciate if you could let me know if you can replicate on a clean Forms install, and if so, share both the exported form and the HTML file you are looking to upload.  Maybe there's something I've missed in attempting to replicate what you've done that this might reveal.

**Comment by AndyButland** [comment]
Thanks for this, but I'm afraid I'm still drawing a blank here.  Let me just replay my test in case you can spot anything I'm missing or have misunderstood.

- Created a new Umbraco site with:

```
dotnet new install Umbraco.Templates::10.6.1
dotnet new umbraco --name TestFormsHtmlUpload
 cd .\TestFormsHtmlUpload\
dotnet add package Umbraco.Forms --version 10.5.1
dotnet run
```

- Clicked through the installer, entering user name and password and otherwise accepting defaults.
- Imported the provided form
- Created two doc types:
    - Thanks page, with rich text editor
    - Home Page, with form picker, allow at root, allow "Thanks page" as child
- Created a home page, picking the form
- Created the thanks page under the home page, entering some text.

- Used the following as the template for the Home page:

```
@using Umbraco.Cms.Web.Common.PublishedModels;
@using Umbraco.Forms.Web;
@using Umbraco.Forms.Web.Extensions;
@using Umbraco.Cms.Core.Configuration.Models;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.HomePage>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
	Layout = null;
}
<html>
<head>
<title>Sample Form Page</title>
</head>
<body>
<h1>Sample Form Page</h1>
@if (Model.Form.HasValue)
{
  @await Component.InvokeAsync("RenderForm", new { formId = Model.Form, theme = "default", includeScripts = true })
}
@Html.RenderUmbracoFormDependencies()

</body>
</html>
```

- Used the following as the template for the Thanks page

```
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.ThanksPage>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
	Layout = null;
}

<html>
<head>
<title>Thanks Page</title>
</head>
<body>
<h1>Thanks Page</h1>
<div>@Model.Text</div>
</body>
</html>
```

- Viewed the home page, selected the second HTML sample provided above as a file called `test.htm` and saw the redirect to the thanks page as expected, with the entry recorded and displayed in the backoffice.

**Comment by nathangchay** [comment]
I replicated the steps you described, and you're correct - the thanks page appears, as expected. In my initial attempt to replicate the issue, instead of using the .NET CLI, I created and ran the project via Visual Studio:

- Open Visual Studio, select 'Create a new project'
- Select the Umbraco Project template, leave settings at default (I have the 10.6.1 templates installed but you may need to run `dotnet new install Umbraco.Templates::10.6.1`)
- Run `Install-Package Umbraco.Forms -version 10.5.1` in the package manager console
- Run the project on IIS Express

After doing this, then following the rest of your steps, I was able to replicate the issue, so I believe it may have something to do with IIS Express. Hopefully you're able to replicate the issue this way!

**Comment by AndyButland** [comment]
Thanks again for the extra info, but I'm sorry to say having followed the Visual Studio/IISExpress route, I could still see the expected behaviour.  It's not clear to me why you should be seeing different behaviour between these hosting options (and also, even if I could replicate, what might be feasible to do about it).

I'll leave this open in case anyone else chips in, but I don't think I can take this further at the moment I'm afraid.

**Comment by nathangchay** [comment]
No worries. I haven't tested this behavior outside of a development environment - if it works as expected on an Azure app service slot (my production environment), then it's a pretty low priority issue, at least for me. If I manage to find anything else I'll report back here. And thanks for your time, regardless!

**Comment by ronaldbarendse** [comment]
> I haven't tested this behavior outside of a development environment

This is definitely something specific to your development environment and probably caused by having [Hot Reload enabled](https://learn.microsoft.com/en-us/aspnet/core/test/hot-reload?view=aspnetcore-6.0), since `aspnetcore-browser-refresh.js` is a script that's automatically injected into your views by VS/.NET and causes the browser window to refresh when file changes are detected (hence you don't see the thank you message/page). Umbraco Forms stores the uploaded files into the media folder, which by default is stored in `wwwroot/media/forms` and the wwwroot folder is [included by default](https://learn.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch?view=aspnetcore-3.1#customize-files-list-to-watch).

You can disable Hot Reload or otherwise configure it to exclude the media directory by adding this to your project file:
```csproj
<ItemGroup>
    <Watch Exclude="wwwroot\media\**\*" />
</ItemGroup>
```

If it's not the .NET Hot Reload feature, it might otherwise be that you have the [Browser Reload on Save](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.BrowserReloadonSave) extension installed, which does something similar...
