### ISSUE TITLE
Forms not showing in tree when creating a new one

### ISSUE THREAD

**Issue by schlindibus** [umbraco/Umbraco.Forms.Issues#1106]
When using Umbraco Forms on my Page, there seems to be a problem, with creating new Forms. I can create one, but after saving it and reloading umbraco, it does not show in the Formtree on the lefthandside.

Reproduction
------------

### Specifics

The Bug occurs in the Form Tab in the backoffice. When creating a new form.
Umbraco Verison: 12.2.0 (Latest)
Umbraco Forms Verison: 12.1.1 (Latest)

### Steps to reproduce

Create a new project, install Umbraco via NuGet and Umbraco Forms. Open the Umbraco, go to Forms Tab, try to create new Form.

### Expected result

When I create a new Form, the new Form should be rendered in the tree on the lefthandside in Umbraco.

### Actual result

The Form was not created. The Console thorws a error: 
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/71329269/6657e41a-550a-430c-a406-bffb119050cd)

**Comment by AndyButland** [comment]
I'm not able to replicate this I'm afraid.  Let me play back what I did following your instructions and maybe you'll spot something different that triggers the issue.

From the command line:

```
dotnet new install Umbraco.Templates::12.2.0
dotnet new umbraco --name Test1106
cd .\Test1106\
dotnet add package Umbraco.Forms --version 12.1.1
dotnet run
```

Then:

 - Installed using SQLite.
 - Logged in
 - Create and form and saved it.
     - Could see it in the form tree and could reload it
 - Refreshed browser
     - Could see it in the form tree and could reload it

**Comment by schlindibus** [comment]
Thanks for your reply. I created a new Project and installed the same Versions of Umbraco and Umbraco Forms as I have in the other project. 

In the Forms section in my appsettings file I added the default configuration as seen here (https://docs.umbraco.com/umbraco-forms/developer/configuration) and it worked. So I knew there'se somethning wrong with my configuration.

When I copied the config from the other project, it didn't work any more. Reason for that was following propertie:
"ManageSecurityWithUserGroups": true,
"GrantAccessToNewFormsForUserGroups": "admin,editor"

When I set it like above, I don't have access to the forms, eventhough my User is Administator, and the Usergroup has all the checkboxes as true:
<img width="549" alt="image" src="https://github.com/umbraco/Umbraco.Forms.Issues/assets/71329269/b0b59ab4-5950-434e-92e4-105dd49c04b1">
<img width="739" alt="image" src="https://github.com/umbraco/Umbraco.Forms.Issues/assets/71329269/08fde2fe-1535-491a-838a-8192137cb7fc">

Funny enough, as soon as I set "ManageSecurityWithUserGroups": false everrything worked perfectly fine. When leaving it on true and set "GrantAccessToNewFormsForUserGroups": "all" it still doesn't work. Maybe ther'se a bug in this property?

For now I can work like that. Thanks for bearing with me :)

**Comment by schlindibus** [comment]
Hi Andy

I've tested it out with different Umbraco Versions, as well with different Forms Versions. As soon, as the Properties are set like this, it doesn't work anymore:

"ManageSecurityWithUserGroups": true,
"GrantAccessToNewFormsForUserGroups": "admin,editor"

Can you test that? Installed a Project with Forms 12.1.1 and Umbraco 12.2.0 as well as Forms 12.0.0 and Umbraco 12.0.1. Both don't work when "ManageSecurityWithUserGroups" is set to true, with whatever "GrantAccessToNewFormsForUserGroups" contains for a value.

Created it as following:
```
dotnet new install Umbraco.Templates::12.2.0
dotnet new umbraco --name TestForms
cd .\TestForms\
dotnet add package Umbraco.Forms --version 12.1.1
```
- Open .csproj in Visualstuido
- Added Form configuration as folowing:
```
"Umbraco": {
  "CMS": {
//Some Cool stuff from Umbraco
  },
  "Forms": {
    "Security": {
      "DisallowedFileUploadExtensions": "config,exe,dll,asp,aspx,js",
      "EnableAntiForgeryToken": true,
      "SavePlainTextPasswords": false,
      "DisableFileUploadAccessProtection": false,
      "DefaultAccessToNewForms": "Grant",
      "ManageSecurityWithUserGroups": true,
      "GrantAccessToNewFormsForUserGroups": "admin,editor"
    }
  }
},
```
- Save file, and start project. From CMD with dotnet run or via VS.
- Setup with SQLLite
- Navigate to Users > Forms Security > Group permissions > Adminisarators > Select all Checkboxes in order to alow everything.
- Save changes
- Go to Forms and create new one. It will show in tree.
- Change "ManageSecurityWithUserGroups": false,
- Run again. Forms not showing in tree.
- Change to "ManageSecurityWithUserGroups": true, again (I'm sorry) to true
- Run again. Forms will not show, eventhough they were showing before.

I'm guessing, that the security configuration is stored in the DB for some reason. Whatever configuration is used when starting the project is the correct one. When creating the steps above, but not adding "ManageSecurityWithUserGroups": true, when starting the project initially, creating a form is possible. As soon as "ManageSecurityWithUserGroups": false, and the permissions on the UserGroup Administrators is given, newly created forms won't show in the tree again.

Thanks for your reply, I'm very intressed what it was.

Greetings Linden

**Comment by AndyButland** [comment]
OK, thanks for the clear replication steps - I can also see the problem now.

In part, you've run into the same issue raised [here](https://github.com/umbraco/Umbraco.Forms.Issues/issues/1102), which we've resolved in the latest, as yet unreleased code, and will make this available in the next round of patch releases.

I suspect though you also need to complete one further step, which will also resolve the issue.  What's partly going on here is that between your install and your restart, you are migrating between storing permissions at the user level to that of the group.  Have a read from [here](https://docs.umbraco.com/umbraco-forms/developer/security#user-group-based-permissions) and in particular the section on [migrating to user group based permissions](https://docs.umbraco.com/umbraco-forms/developer/security#migrating-to-user-group-based-permissions),

Effectively when you move to `ManageSecurityWithUserGroups: true` you probably also want to remove the previously created user level permission record in order for your permissions to inherit from the groups.  You only need a record under _Forms Security > User permissions_ if you have specific rules for a given user that you want to override what is set by the groups they are in.  Normally this isn't needed, and so as part of the move from user managed permissions to group managed ones, you'll want to delete the previously existing user level records.

I'll close this as a duplicate due to the part that needs fixing being addressed by the other linked issue.
