### ISSUE TITLE
Submitting multiple fields with conditions does not store the answers.

### ISSUE THREAD

**Issue by Xiaohao-Ye** [umbraco/Umbraco.Forms.Issues#1111]
A multi choice question with independent conditions doesn't store the values of multiple fields with conditions. A Form is set up like this:
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/105862841/3f23ecb2-697c-45b4-83f9-6dc9201d9bde)

Reproduction
------------
### Bug summary

When the form is set up like in the screenshot and you check both option in Question 1 and fill in Question 2 and Question 3 and submit the form the answers of Questions 2 and 3 the answers are not stored.

### Specifics

This is not on a public URL right now. We changed the form because this did not work. We tested this using Umbraco Forms versions 10.5.1 and using a custom theme and also the default theme in Chrome version 118.0.5993.118.

### Steps to reproduce

Set up the form like in the first screenshot and check both options in Question 1. Fill in Question 2 and 3.
Check the result. It should look like this:
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/105862841/23690f7e-d2e5-4856-9051-21a272389b7b)

### Expected result

The answers of Question 2 and Question 3 are both stored and visible. In the browser we see the answers are submitted in the browser:
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/105862841/b0fe3850-2d7d-4a8d-92de-d69d2e4a9457)

### Actual result

The answers of Question 2 and Question 3 are missing. When we only check one option in Question 1 and fill in the question that is shown, the answer filled in there is stored:
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/105862841/ba8de356-5205-470e-a52b-e0acfbcc85bc)

**Comment by AndyButland** [comment]
It sounds like there's a subtle discrepancy between the client and server side validation for conditions - client-side it's accepting your entry but server-side it's consider invalid so not stored.  Would be good to ensure this is fully aligned certainly, but I think the issue in your case stems from the first condition you have - you asking to show "Question 2" if "Question 1" **"is"** "A".  But when you select both, it's not "A" it's "A" and "B".

So I think if you change the first condition to be using the **"contains"** operator instead of "is", it should work as you expect.

**Comment by Xiaohao-Ye** [comment]
@AndyButland This was the issue, thansk for clearing it up.
