### ISSUE TITLE
Umbraco.Forms 13.1.2 records are missing an IP address when the site is behind Cloudflare CDN

### ISSUE THREAD

**Issue by stephen-sherman** [umbraco/Umbraco.Forms.Issues#1245]
### Bug summary

Umbraco.Forms 13.1.2 records are missing an IP address when the site is behind Cloudflare CDN.

### Specifics

Observed in multiple solutions running Umbraco.Forms 13.1.2 behind Cloudflare CDN.

- The `EnableRecordingOfIpWithFormSubmission` configuration is enabled (by default, [documentation](https://docs.umbraco.com/umbraco-forms/developer/configuration#enablerecordingofipwithformsubmission)).
- The recommended [header forwarding](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-8.0) middleware is being used.
- The `X-Forwarded-For` header is being populated with the user's IP address.

This seems similar to Issue #1000, though I can't find any documentation about how to use the fix outlined therein.

### Steps to reproduce

- Create a solution running Umbraco Forms 13.1.2.
- Deploy the site behind Cloudflare CDN.
- Create a form.
- Submit a form record.
- Look at the `IP` column of the record in the `UFRecords` database table.

### Expected result

The user's IP address is stored in the `IP` column of the record in the `UFRecords` database table.

### Actual result

The `IP` column of the record in the `UFRecords` database table is empty.

**Comment by AndyButland** [comment]
Seems our documentation has got a bit our of date here, so sorry for the confusion if that turns out to be the case.

On the linked issue - I've added a comment there - but in fact those options weren't in the end released and hence that's why they aren't documented.

As of Forms 12, `EnableRecordingOfIpWithFormSubmission` is disabled by default.  So it might be just that you need to explicitly enable that by setting the option to `true`.

If you've done that, it would be worth independently inspecting what you have coming through for `httpContext.Connection.RemoteIpAddress` in your environment.  As that's what is read by Forms to populate this field.

Meantime, I'll create a PR to get the docs up to date...

**Comment by stephen-sherman** [comment]
Thanks Andy, confirming that this was indeed caused by a change in the default setting of `EnableRecordingOfIpWithFormSubmission`. It is now capturing IP addresses as expected with this explicitly set to `true`.
