### ISSUE TITLE
Umbraco Forms Performance

### ISSUE THREAD

**Issue by MarkCullen1977** [umbraco/Umbraco.Forms.Issues#125]
Hello, this is a ticket split from
https://github.com/umbraco/Umbraco.Forms.Issues/issues/97
This is an Umbraco Gold Partner query (Screenmedia).

We have been load testing our Umbraco environment using MS load tests in visual studio. It is a simple solution which is comprised of a few Umbraco forms.
The Umbraco form we are testing has a custom work-flow attached, which connects to an API and updates the underlying form record using the response of the API call.

The form is quite simple, containing roughly 28 different fields.

Our app is hosted on an Azure p1v2 web app, and the database has 50 DTUs (S2)

We are using Umbraco 7.12.3 & Umbraco Forms 7.0.3

We have found that when load testing users hitting the site over a period of 5 minutes that the performance is quite slow.

For example

25 users
The application slows down significantly with a load of 25 users hammering the application at the same time, but the application remains available and there are no failures reported. Average POST time is 7.62 seconds and the average GET time is 1.08 seconds. Average CPU utilization on the app service plan increased steadily, spiking just once under 90%. Database DTU (Data Throughput Unit) utilization reached 100%, indicating heavy load on the database

100 users
Under constant load of 100 users the application performs very poorly. Here, average POST time is 28.9 seconds, and average GET time is 11.9 seconds. Average CPU utilization on the app service plan reached just under 100%, with some relief in between peaks. DTU consumption spiked approaching 100% on a few occasions with a short drop in between

This shows that the infrastructure is not coping well with the volume of requests.
In addition there were 50 failed requests / tests. These were due to the server being overwhelmed with requests. These appear to be timeouts where the POST request timed out.

We would not expect the infrastructure to have difficulty coping with this number of requests. When we look at application insights we see there is a lot of WAIT time as tasks get stuck waiting for resources, and also there is a considerable spike in the CPU thread count.

In looking at Umbraco forms it was found that
•	Not saving the data to the database greatly improved performance
•	Not executing the custom workflow increased performance on the POST request. Infact, it was found that the workflow task was poor even it had essentially an empty body, i.e not doing anything.

In summary it seems like there are some performance issues with Umbraco forms in both writing to the DB and also in using custom work-flows. Perhaps optimizing the process above will help but also looking at how and when the system locks threads might be an idea?

**Comment by ronaldbarendse** [comment]
Issue #69 is probably related to the slow GET response-time, as you're using a lot of fields and for every one Forms is doing a `File.Exists`, causing a lot of unnecessary disk I/O.

The record fields are also saved as seperate rows (`UFRecordFields`), in different tables per field type (`UFRecordDataBit`, `UFRecordDataDateTime`, `UFRecordDataInteger`, `UFRecordDataLongString` and `UFRecordDataString`) _and_ as JSON value in `UFRecords.RecordData`. This probably causes the slow POST response-time, as it has to create/update/read multiple tables to keep the data in sync. And looking at the SQL queries it generates, it fetches each field value in a seperate query, instead of using a single query with inner-joins or even grouping them per table/type...

This is all besides the task-based workflows, which can even be run asynchronously using the setting `ExecuteWorkflowAsync` (in UmbracoForms.config). If you require the record to be updated (by the workflow) before displaying the submit message, async workflows will not help though 😉

**Comment by nul800sebastiaan** [comment]
Not sure how this issue is different from #97, the description seems the same. I'll close this for now.

**Comment by ronaldbarendse** [comment]
@nul800sebastiaan I don't think the performance suggestions about retrieving (and storing) the record values in a single SQL query is implemented yet. That's a major issue causing the slow performance, especially when `Store Records` is enabled (as described in this issue).

**Comment by nul800sebastiaan** [comment]
But that's a new issue, this was a copy of #97.. I am happy to copy your comment to a new issue if that's what's needed, if I understand correctly?

**Comment by ronaldbarendse** [comment]
I've created a new issue for it 👍 So both my comments now have their own issue: https://github.com/umbraco/Umbraco.Forms.Issues/issues/69 and https://github.com/umbraco/Umbraco.Forms.Issues/issues/294.
