### ISSUE TITLE
Form Submissions with datepicker returns empty, does not capture the value in backoffice, its empty

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco.Forms.Issues#1255]
This is same as the issue https://github.com/umbraco/Umbraco.Forms.Issues/issues/1209 and I can reproduce this when I upgraded to 13.1.2

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

**Comment by AndyButland** [comment]
I'm not seeing this with the latest release @poornimanayar - could I trouble you to please?

- Make sure you have definitely [fully cleared the browser cache](https://www.andybutland.dev/2022/09/backoffice-cache-busting-with-umbraco.html)
- Let me know if you are running a custom theme (and if so, if it's possible to share it with me)?
- If it's feasible to do so, check with 13.2.0-rc1

Thanks

**Comment by poornimanayar** [comment]
Of course you can trouble me Andy! I will check and get back to you😃

**Comment by poornimanayar** [comment]
@AndyButland , I tried in incognito mode and it does not work. We haven't got any customisations to theme. I cant try 13.2 RC as the site is in production

**Comment by AndyButland** [comment]
Hmm... I figured it would be good to test on the version you are running rather than with the latest release candidate, but I still don't see the issue I'm afraid.

Let me just play back what I've done - maybe you can try this too to see if actually you do see the issue with a clean install, or if like me you don't, maybe it helps to identify what's different in your setup.

---

From the command line:

```
dotnet new install Umbraco.Templates::13.4.1
dotnet new umbraco --name TestProject
cd .\TestProject\
dotnet add package Umbraco.Forms --version 13.1.2
dotnet run
```

Then installed using SQLite.

Created a form with a date field (I used the "Contact form" template, and then added a new date field to it).

Created a home page document type, allowed at root and added a form picker property to it with an alias of `form`.

Updated the template to:

```
@using Umbraco.Cms.Web.Common.PublishedModels;
@using Umbraco.Forms.Web;
@using Umbraco.Forms.Web.Extensions;
@using Umbraco.Cms.Core.Configuration.Models;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.HomePage>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
	Layout = null;
}
<html>
<head>
<title>Sample Form Page</title>
</head>
<body>
<h1>Sample Form Page</h1>
@if (Model.Form.HasValue)
{
  @await Component.InvokeAsync("RenderForm", new { formId = Model.Form, theme = "default", includeScripts = true })
}
@Html.RenderUmbracoFormDependencies(Url)

</body>
</html>
```

Created the content item.

Loaded the front-end website, completed the form and provided a date value.

Confirmed I'm seeing the date when I view the entry in the backoffice

**Comment by poornimanayar** [comment]
I can confirm that with 13.2 and the files updated for the custom theme, this is no longer an issue. Thank you for your help @AndyButland
