### ISSUE TITLE
Edit custom workflow shows wrong name/description for custom properties, missing include sensitive data flag  (V14)

### ISSUE THREAD

**Issue by arcjawsh** [umbraco/Umbraco.Forms.Issues#1260]
### Bug Description

When viewing custom workflow in the back office, custom properties decorated with the Setting attribute do not show the right label or description. Include sensitive data flag also appears to be missing. Only applicable in Umbraco 14 / Forms 14.

![u14forms_setting](https://github.com/user-attachments/assets/e5ca1798-41dc-495a-b40a-a27777df1969)

![u14forms_code](https://github.com/user-attachments/assets/58946563-c434-43df-b6ba-792392da34bc)

### Specifics

Umbraco 14.0.0
Umbraco Forms 14.1.0
Edge / Chrome
/umbraco/section/forms/workspace/form/edit/{formId}/view/design

### Previous Behaviour:
Umbraco 13.4.0

![u13_setting](https://github.com/user-attachments/assets/44a47872-a5f1-497e-9da6-792b9b547e5c)

**Comment by nathanwoulfe** [comment]
Hey @arcjawsh I believe the labelling is due to these values now being localized rather than using the static text defined in the Setting attribute. The documentation at https://docs.umbraco.com/umbraco-cms/extending/language-files/ui-localization explains how to add your own localizations.

 The sensitive data toggle might be an oversight on our part, will need to look into that one.

**Comment by arcjawsh** [comment]
@nathanwoulfe Thanks for the prompt response - that was exactly it, thank you.

Did you want me to close this issue and make another for the missing sensitive data flag ?

**Comment by nathanwoulfe** [comment]
That would be great, thank you.
