### ISSUE TITLE
Issue while adding Umbraco form in Uskinned components

### ISSUE THREAD

**Issue by anzalnanazar896** [umbraco/Umbraco.Forms.Issues#1269]
Hello,

I am experiencing an issue with my Uskinned in Umbraco setup where I encounter a UNIQUE KEY constraint violation on the umbracoRelation table. The error message is as follows:

![umbracoerror](https://github.com/user-attachments/assets/1a4b69c8-eaf7-4e05-ae48-22368552d36d)

I have checked the umbracoRelation table and found that there are already two records with the following details:

SELECT * FROM umbracoRelation WHERE parentId = 6367 AND childId = 6365 AND relationType = 6;

One record with relType = 4 and another record with relType = 6

It seems like the system is trying to insert a duplicate key for the relation type 6.

I got the issue while adding Umbraco form inside a Uskinned component.

How can I resolve this issue?

**Comment by Dark0d3** [comment]
It appears that the only solution I've discovered to the problem is to drop the constraint, which can fix the problem.

`-- Dropping the constraint
ALTER TABLE [umbracoRelation]
DROP CONSTRAINT [IX_umbracoRelation_parentChildType];

-- Re-adding the constraint if needed
ALTER TABLE [umbracoRelation] 
ADD CONSTRAINT [IX_umbracoRelation_parentChildType] 
UNIQUE NONCLUSTERED ([parentId], [childId], [relType]);`

maybe someone can mark this as an issue and look into it further

**Comment by AndyButland** [comment]
That workaround doesn't sound ideal, as the CMS constraint is likely there to protect against duplicate records which it won't be expecting to handle.

I think you will probably have to first take this up with uSkinned please.  Maybe they aren't doing anything in particular here with regard to relations but at least they'll be able to verify that it's not caused by some custom code they are running, can provide details of version used and perhaps can provide replication steps in a standard CMS and Forms installation.

I'll keep this open for now in case you or they can provide this further detail.

**Comment by anzalnanazar896** [comment]
I have installed Umbraco CMS **12.3.10** and Umbraco Forms **12.2.2**. Worked on both standard CMS and Uskinned solution. Again the issue was generated while adding umbraco Forms .

Uskinned Solution 

![image](https://github.com/user-attachments/assets/e49303cd-89be-452e-bdff-99e2385b2504)


Standard CMS 

1. Created a template page **Home** and a block **Form Picker**
![image](https://github.com/user-attachments/assets/27a5151e-7814-4feb-8f3a-6ca595c23c90)

2. Rendered the form inside home page using blocklist.

![image](https://github.com/user-attachments/assets/06c0dbdf-53be-4cd5-90e3-adf202ffbfd2)

The issue is 
![image](https://github.com/user-attachments/assets/0976981a-b7c7-469d-96fb-f63aa8bb994a)

Any solution for this ?

**Comment by AndyButland** [comment]
OK, I recognise it now as the same issue raised in https://github.com/umbraco/Umbraco.Forms.Issues/issues/1129.  You'll see linked from that issue there are some workarounds - you can disable the relation tracking for forms, add an [unused form picker to the document](https://github.com/umbraco/Umbraco.Forms.Issues/issues/1129#issuecomment-1854426349) or upgrade to Forms 13.

**Comment by anzalnanazar896** [comment]
Thank you @AndyButland. It got fixed when added the workaround in the config.
