### ISSUE TITLE
Missing dictionary support for label in backoffice

### ISSUE THREAD

**Issue by Alkaersig** [umbraco/Umbraco.Forms.Issues#1273]
Reproduction
------------

### Bug summary
This label in the workflow section (bottom) of the form view in backoffice is missing dictionary support.
![image](https://github.com/user-attachments/assets/10fe9ebd-b97b-4eae-86b8-07691f4a903a)

We are using Magic Strings as default values for all our forms labels so the customers wont have to insert them manually everytime they create a form. It works perfect when the forms are rendered outside of Umbraco but it seems this label uses the default values from the configuration as well and does not support dictionary values.
![image](https://github.com/user-attachments/assets/ab7ee35d-3fe7-4783-8c4d-39993630a9f2)

### Specifics
Tested in Forms 13.1.2 and 13.2.0.

### Steps to reproduce
Replace the "SubmitButtonLabel" in Forms Configuration with a Dictionary Item Magic String. Instead of the dictionary value the Magic String will get rendered in Umbraco UI.

### Expected result
The Dictionary Item value should be rendered

### Actual result
The Magic String is rendered

**Comment by AndyButland** [comment]
I think here really we should just be providing a standard backoffice label, i.e. one that's localizable via the XML files that ship with or are added to Forms.  The dictionary translations are indented really for use on the front-end website,

Currently what's happening is we get the raw value for this field when we load the form for editing in the backoffice - and we need that, not the translated one, so you can edit it via the "Settings" tab.  

At some point it was probably thought nice if we display the customised label rather than just the default of "Submit" in the screen you have shared above.  But it doesn't work when you have a "magic string" here, so I think it's best and fine for a backoffice label to just have a fixed label of "On Submit" (like we have for "On Approve").  So we'll do that for the next patch releases.
