### ISSUE TITLE
Custom Workflow Settings not displaying property fields

### ISSUE THREAD

**Issue by rizman** [umbraco/Umbraco.Forms.Issues#1299]
Some time ago I started work on a custom workflowtype and it worked (don't remember which version of Umbraco Forms that was with). I got interrupted.

Since then, I upgraded to v14.1.3 (same behaviour with 14.1.2)

Here is the code for my test custom workflow:

`
using Umbraco.Forms.Core.Enums;
using Umbraco.Forms.Core;
using Umbraco.Forms.Core.Attributes;

namespace FormsExtensions
{

    public class TestWorkflow : WorkflowType
    {
        [Setting("Test", 
            Description = "Test description", IsMandatory = true
            )]
        public string TestProperty { get; set; }

        [Setting("Test2",
           Description = "Test description", IsMandatory = true, View = "TextField"
           )]
        public string TestProperty2 { get; set; }

        public TestWorkflow()
        {
            this.Name = "Test";
            this.Id = new Guid("E6A2C406-CF89-11DE-B075-55B055D89593");
            this.Description = "Test Workflow";
        }

        public override Task<WorkflowExecutionStatus> ExecuteAsync(WorkflowExecutionContext context)
        {
            return Task.FromResult(WorkflowExecutionStatus.Completed);

        }

        public override List<Exception> ValidateSettings()
        {
            var list = new List<Exception>();
            return list;
        }
    }
}
`

I see it on Umbraco Forms backend, but the labels are not shown correctly:
![image](https://github.com/user-attachments/assets/ac991dab-c5e4-443b-aa48-5ee3f7a23f67)

I have the same with a custom workflow I tried to copy from y Gist (Post to URL as JSON):
https://gist.github.com/hetfirma/b0da14502f0cbf1e3d4f99707a45da9d

Is this probably a bug or am I missing something?

Kind regards

**Comment by AndyButland** [comment]
Yes, it looks like you are missing a couple of things with the move to 14.

One is the names of the views - they are now property editor UIs - so `View = "TextField"` isn't recognised and that's why your second field is missing.  See description of the `View` attribute [here](https://docs.umbraco.com/umbraco-forms/developer/extending/adding-a-fieldtype#field-settings).

Then you need a front-end file with the translations for these labels (see [here](https://docs.umbraco.com/umbraco-forms/developer/extending/adding-a-fieldtype#language-files)).

It's worth a read of that page from top to bottom actually, as there are a few changes in this area when it comes to 14, particularly if you are looking to use your own property editor UI.

One more useful page is this [one](https://docs.umbraco.com/umbraco-forms/developer/extending/adding-a-type/setting-types#built-in-setting-types), which will detail which property editor UIs are used on the existing setting types provided in the package.

**Comment by rizman** [comment]
Hi @AndyButland ,
Thansk for your reply and sorry to have filed this as an issue. I should have read the doc more carefully since moving to v14.

I will try it later on.

Kind regards

**Comment by AndyButland** [comment]
No problem.  I'll close this issue but please feel free to raise a new one if you run into problems.

**Comment by sirreini1** [comment]
i cant get it to work. i tried by adding a umbraco-package.json file to the App_PLugins folder.
i tried to follow the documentation here: https://docs.umbraco.com/umbraco-cms/14.latest/customizing/extending-overview/extension-types/localization
i also tried this here: https://docs.umbraco.com/umbraco-forms/developer/extending/adding-a-fieldtype#language-files
but only the last part with the localization. this did also not work because the  "ManifestLocalization" type can not be imported as in the documentation stated. 

this is the label i get right now for the linktext setting: 
![grafik](https://github.com/user-attachments/assets/6ec3cf68-4aeb-4666-a7ef-ecee69255ca6)

this is the js file i used: 
```export default {
    "dashboardTabs": {
        "umbracoForms": "test"
    },
    "formProviderFieldTypes": {
        "linkTextLabel": "Link Text",
        "fieldSettings": {
            "linkTextLabel": "Link Text",
        }
    },
    "fieldSettings": {
        "linkTextLabel": "Link Text",
    }
}
``` 
This is the umrbaco package json
```
{
  "$schema": "../umbraco-package-schema.json",
  "name": "Umbraco.Forms.Extensions",
  "extensions": [
    {
      "type": "localization",
      "alias": "UmbracoForms.Localize.en-Us",
      "name": "test",
      "meta": {
        "culture": "en-US"
      },
      "js": "App_Plugins/FormLocalization/form-link-type-localization.js"
    }
  ]
}
```

**Comment by AndyButland** [comment]
Sounds like you might be missing - and we may be missing in the documentation - some updates related to [these changes](https://github.com/umbraco/Announcements/issues/22) between Umbraco 14 and 15.  At least I believe that explains where `ManifestLocalization` has gone.  Checking in the Forms code I can see we import this from:

```
import type { ManifestLocalization } from '@umbraco-cms/backoffice/localization';
```

**Comment by AndyButland** [comment]
Docs PR is here: https://github.com/umbraco/UmbracoDocs/pull/6729

**Comment by Gavin5656** [comment]
Belatedly picking up on this one as I've just started migrating a v13 site to v14. The forms documentation here: [https://docs.umbraco.com/umbraco-forms/developer/extending/adding-a-fieldtype#language-files](url) states:

_Setting labels and descriptions can be translated via language files. If no client-side localization is provided, the values provided server-side in the Setting attribute's Name and Description properties will be used._

That doesn't appear to happen e.g. 
```
    public class FieldInfoLabel : FieldType
    {
        [Setting("Label Text", Description = "Text or markup to show", View = "Umb.PropertyEditorUi.TextArea")]
        public string LabelText { get; set; }
```
In my UI, I still just see:
**formProviderFieldTypes_LabelTextLabel
formProviderFieldTypes_LabelTextDescription**

I don't have a language file and the values from settings aren't reflected in the UI. Is the documentation just wrong and we need client-side files in all cases, or do we have a bug here?
