### ISSUE TITLE
Toggle missing from "Sensitive Data" on Field configuration

### ISSUE THREAD

**Issue by robertjf** [umbraco/Umbraco.Forms.Issues#1309]
A brief description of the issue goes here.

When adding a new field, the Sensitive Data property has no toggle to turn it on or off:

![image](https://github.com/user-attachments/assets/ddbd3288-94b0-4a83-92ab-d985d69fb6fb)

I tried adding a Short Text field in this case on Umbraco Forms 13.2.5

**Comment by AndyButland** [comment]
Thanks @robertjf - I can replicate.  This looks to be a regression introduced in resolving https://github.com/umbraco/Umbraco.Forms.Issues/issues/1233.

We want the behaviour to be that you see this message only if aren't in the "sensitive data" user group and the field has previously been toggled to on.  It's actually working correctly once you've added the new field and saved the form - you can then see the toggle.  But it's not working correctly on the initial action of adding a new field.

This will be fixed in the next release for Forms 13.
