### ISSUE TITLE
Problem with MultiPage form - NEXT button not does not switch to page 2

### ISSUE THREAD

**Issue by aabib** [umbraco/Umbraco.Forms.Issues#1342]
A brief description of the issue goes here.

Reproduction
------------

1. Umbraco forms created in backend
2. Forms are linked to frontend
3. The form is displayed fine on frontend https://bhpd.dk/sommerstaevne/tilmelding/tilmelding-2025/
4. The form is filled in - Page 1
5. Press the NEXT button
6. The form is submitted and page 2 is not displayed

There are three pages in total but I can't get the system to move on to page 2
I have followed the instructions but can't get it to work

**Comment by AndyButland** [comment]
Could you export your form please and we can have a look?

**Comment by AndyButland** [comment]
I don't see the form I'm afraid.  You should be able to attach the exported json file to this issue in GitHub.

**Comment by AndyButland** [comment]
What version of Forms are you running please?

**Comment by AndyButland** [comment]
OK... so I ran into one bug I had to resolve before I could get this form to work, but oddly it isn't the one you have reported.

I found an issue with the "max length for fields" checks.  You have a validation on the "Alder ved stævnets begyndelse" field to limit it to 2 characters, but the bug I've found is that this is being applied to another field that is allowed to be longer than this.  So that was preventing me submitting the form.

When I fixed that though, the form went on to page 2 as expected for me.

It doesn't seem related, but maybe temporarily remove that restriction and see if the form then works as expected?  If so, I'll get this bug resolved for the next release (which will be out in a release candidate tomorrow).  If not, we'll need to look further.

**Comment by AndyButland** [comment]
Hmm... probably was unrelated then.  Again I don't see the form I'm afraid, so perhaps you could attach to this issue.

Otherwise are you using a custom theme for your implementation, or have you just styled the default theme that Forms ships with?

**Comment by AndyButland** [comment]
OK, I'm having trouble seeing the problem in my setup I'm afraid.

Can I suggest you try it in a minimal template please, something like the following - just to see if you see the problem there, and if not, maybe it's something else on the page interfering with it?

```
@using Umbraco.Cms.Web.Common.PublishedModels;
@using Umbraco.Forms.Web;
@using Umbraco.Forms.Web.Extensions;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.HomePage>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
	Layout = null;
}
<html>
<head>
</head>
<body>
@if (Model.Form.HasValue)
{
  @await Component.InvokeAsync("RenderForm", new { formId = Model.Form, theme = "bootstrap3-horizontal", includeScripts = true })
}

@Html.RenderUmbracoFormDependencies(Url)

</body>
</html>
```

**Comment by AndyButland** [comment]
I don't see anything wrong, but as I suggested above, could you try it in a minimal template like the one I provided please?

And if you've customised the `Form.cshtml` file, remove it so you are using the default one shipped with Forms.

Hopefully in doing that you'll find a situation where it works and we can discover if there's something that different in the actual templates you are using that is causing the issue.

**Comment by AndyButland** [comment]
Sorry if you've tried this and just not stated, but I've suggested a couple of things above and I'm not sure if you have given them a go yet.  If you have, could you report back on the results?  Or if not, could you try them - it will help isolate where the problem is coming from (e.g. something in your page template like a script, something in customisations you may have made to the form rendering partial view).

> I don't see anything wrong, but as I suggested above, could you try it in a minimal template like the one I provided please?

> And if you've customised the Form.cshtml file, remove it so you are using the default one shipped with Forms.

I don't think Visual Studio version should have any impact here.

**Comment by AndyButland** [comment]
Please see my previous comment:

> And if you've customised the Form.cshtml file, remove it so you are using the default one shipped with Forms.

As I think the issue may be here.  You did post your `Form.cshtml` up above, but it got garbled when it came through your update via email.

It should have an element like this though:

```
    <div class="umbraco-forms-hidden" aria-hidden="true">
        <input type="text" name="@Model.FormId.ToString().Replace("-", "")" />
    </div>
```

This is the "honeypot".  If a bot fills it with a value we assume it is a bot submission and not one from a user.

If I view the source on your website I can see it comes already completed with a value:

```
<div class="umbraco-forms-hidden mt-2" style="display:none;">
   <input type="text" name="d796df4a308f4b52bb5210e166ba5199" value="d796df4a308f4b52bb5210e166ba5199" />
</div>
```

You can go back to using your custom one, but you will need to amend it to ensure this field doesn't have a value when the form is rendered.

**Comment by AndyButland** [comment]
It's not, but if you've solved your problem, all good.
