### ISSUE TITLE
Translation not working for placeholders

### ISSUE THREAD

**Issue by GertyEngrie** [umbraco/Umbraco.Forms.Issues#185]
When creating a form and using the # syntax for translating fields ( f.e. #requestTitle -> dictionary item: requestTitle) the placeholder is not translated. So i'm using #requestTitlePlacholder in the placeholder setting field but the rendered form is showing #requestTitlePlaceholder as placeholder instead of the value of my dictionary item. 

Reproduction
------------
### Bug summary
Placeholder is not being translated

### Specifics
Version: UmbracoForms v8.1.1 , Umbraco 8.0.2
Browser: Chrome

### Steps to reproduce

Create a form with a field, use #requestTitlePlaceholder as placeholder value, create a dictionary with the same name ( without #) and render the form. 

### Expected result

I expected to see the value of the dictionary item

### Actual result

The text I wrote in the dictionary field. 

---
_This item has been added to our backlog [AB#1846](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/1846)_

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Forms/pull/293

**Comment by Splinx** [comment]
This issue appears not to be working on **Umbraco forms 7.3.1**.

**I can confirm that the #values are replace for**
Name - PASS
Default value - PASS
Validation - PASS

**but not...** 
Place holder - FAIL

I upgraded forms specifically for this fix which is incredibly important due to localization - without it we cannot use placeholder at all and don't want to be stuck with multiple forms (one for each of the 12 locales).

I apologize in advance if I should not have reopened this item.  I thought it was probably the most appropriate place as this has clearly been resolved in version 8.

Thanks,
Splinx

**Comment by GertyEngrie** [comment]
if you really want it you can just edit the partial used for rendering :-)

**Comment by Splinx** [comment]
Cool - thanks for the tip :)

**Comment by Splinx** [comment]
> if you really want it you can just edit the partial used for rendering :-)

Do you know exactly where this is please (assuming you've done it before).

Cheers,
Splinx :)

**Comment by GertyEngrie** [comment]
Depending on your version: 
/views/partials/Forms/Fieldtypes/* or /views/partials/Forms/Themes/default (or the theme you are using)/Fieldtypes/* -> edit the partial you need.
