### ISSUE TITLE
Settings Not Saving and Displaying

### ISSUE THREAD

**Issue by ShaneDPorter** [umbraco/Umbraco.Forms.Issues#264]
When trying to save settings like placeholder text, upon hitting save and refreshing the page where the form is located, no placeholder text displays. Upon refreshing the form editor page and reopening the questions, the previously saved placeholder text box is empty. This was first discovered when trying to add a recapcha to my form. After hitting save, it wiped all of my previously saved (and displaying) labels and place holder text. 

I was instructed by Michael Roholdt Larsen to report this bug

Reproduction
------------
### Bug summary

Whenever I try to save settings on the contact form that I have created, some of the information doesn't save. The best example of this is the placeholder text. I will add placeholder text to the form, hit save, open the page where the form exists only to see that the placeholder text isn't present. Upon refreshing the form editor page and opening the answer, it's made clear that the placeholder text wasn't saved as the entry bar is empty. 

### Specifics

Umbraco version 8.4.0 project running Umbraco Forms: 8.2.0
Links for where the bug is displayed as well as project admin access is available. Should anyone require this, please email me on shane.porter@fwdmotion.co.uk with an umbraco email address.

### Steps to reproduce

1. Login into Umbraco
2. Edit form field, adding a placeholder
3. Save form
4. Refresh page and see placeholder empty despite being set
5. Reopen umbraco forms page and see that the placeholder text entered is no longer present.

### Expected result

All Umbraco Forms settings to save.

### Actual result

Umbraco forms settings don't save.

**Comment by rbottema** [comment]
We are seeing the same issue with workflows not being saved. This is an important issue, so any ideas for workaround are also welcome. I dove into the (decompiled, as Forms is not open source) code and I think I found the cause.

When saving the workflow, there is a settings field with multiple setting objects, which have (among others) an `alias` and a `value`. For example, for the 'send email' workflow there is a setting with alias `Email`. When this workflow is saved to the file system, the settings have transformed to a single JSON object, where the keys are the `alias` and the values are the `value`. However, this alias is now saved as `email` (so, made lowercase).
When reading the configuration again, in `GetWithWorkflowsByGuid` in `Umbraco.Forms.Web.Editors.FormController`, the code does a `SingleOrDefault` on `x.Key == workflowSetting.Value.Alias`. However, because `xKey` here is `email` and `workflowSetting.Value.Alias` is `Email`, the loading fails and nothing is displayed. I have confirmed that when I manually change the key in the saved Json to `Email`, the email is loaded correctly.

As Forms is not open source, I can not make a quick change and recompile, so I am a bit stuck on how to implement a workaround at this point. Any input is greatly appreciated.

**Comment by rbottema** [comment]
Turns out we were doing the following in our `WebApiConfig.Register`:
```
config.Formatters.JsonFormatter.SerializerSettings.Converters.Add(new StringEnumConverter());
config.Formatters.JsonFormatter.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
JsonConvert.DefaultSettings = () => config.Formatters.JsonFormatter.SerializerSettings;
```
Removing that last line fixes the issue for us. Maybe that also works for you @ShaneDPorter?

I don't know much about this, perhaps Umbraco Forms should (more) explicitly define the format is uses when serializing?

**Comment by ShaneDPorter** [comment]
Thank you so much @rbottema, we had the same issue.
Here is our code for reference:

```namespace Example.Core.Composers
{
    [RuntimeLevel(MinLevel = RuntimeLevel.Run)]
    public class JsonConfigurationComposer : IUserComposer
    {
        public void Compose(Composition composition)
        {
            JsonConvert.DefaultSettings = () => new JsonSerializerSettings
            {
                ContractResolver = new CamelCasePropertyNamesContractResolver()
            };
            MediaTypeFormatterCollection formatters = GlobalConfiguration.Configuration.Formatters;
            JsonMediaTypeFormatter jsonFormatter = formatters.JsonFormatter;
            JsonSerializerSettings jsonSerializerSettings = jsonFormatter.SerializerSettings;
            jsonSerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
            jsonSerializerSettings.NullValueHandling = NullValueHandling.Ignore;
        }
    }
}
```

**Comment by nul800sebastiaan** [comment]
Great to see this is being worked around, I'll change this issue into a feature request instead for Forms to be more specific in requesting a certain formatter! 👍

**Comment by JohnBertelsen** [comment]
Any news on this. any plans on fixing this bug, as it still persists in Umbraco Forms 8.8.0

**Comment by AndyButland** [comment]
We've added specific set of settings for serialization to all operations within Forms now, such that if the default is set to something else that won't change how Forms does it's own serialization and deserialization.
