### ISSUE TITLE
Page and Group Intro / Footer formatted text

### ISSUE THREAD

**Issue by jstrugnell** [umbraco/Umbraco.Forms.Issues#280]
It would be great if there were some additional options within the Page and Group configuration , to add formatted text at the top and bottom. So we would be able to add lengthy, formatted text at the top and bottom of each page, and also at the top and bottom of each group.

**Comment by nul800sebastiaan** [comment]
This can already be achieved by implementing a custom field type that, instead of outputting a form field, will just output the text you enter in a setting. 
https://our.umbraco.com/documentation/Add-ons/umbracoforms/developer/extending/adding-a-fieldtype

The settings for a fieldtype don't currently include a rich text editor, but you can draw some inspiration from this project where it's been added:
https://github.com/lars-erik/our.umbraco.forms.contrib

For more interesting functionality and inspiration (it's open source) also check out this project: https://our.umbraco.com/packages/backoffice-extensions/umbraco-forms-on-perplex-steroids/

It's a great suggestion though! This one is going on our ideas list for new features to implement in the future. Please keep an eye on our roadmap, it will give you an idea of where our software products are going.

**Comment by jstrugnell** [comment]
Thanks. I did find an example here - https://github.com/east-sussex-county-council/Escc.Umbraco.Forms.

I had to tweak the code a little to get it working in V8, but it seems to be working well. The above suggestion might be a more complete and intuitive solution though, so hopefully it will make the cut.

Cheers.

**Comment by AndyButland** [comment]
In the next release we'll be adding a rich text field type, which could be used for this scenario.  For Umbraco 8 there's already a [package available](https://our.umbraco.com/packages/backoffice-extensions/umbraco-forms-rich-text/), so we'll add this for Forms 9 and 10.

**Comment by Wiggee11** [comment]
@AndyButland Where can I find the field type view "FieldType.RichText.cshtml" for this?

The U10 theme download zip does not include it - https://our.umbraco.com/documentation/add-ons/umbracoforms/Developer/Themes/

**Comment by AndyButland** [comment]
You can get it from [here](https://our.umbraco.com/FileDownload?id=23911) (I'll also update the link on that page).
