### ISSUE TITLE
Duplicate Emails sent out on form submission

### ISSUE THREAD

**Issue by rogermal** [umbraco/Umbraco.Forms.Issues#291]
Duplicate Emails sent out on form submission

Reproduction
------------
See steps below

### Bug summary
Duplicate Emails sent out on form submission

### Specifics
   Occurs on all browsers. We are using Umbraco V 7.7.13 and forms V6.0.6 .
   No error messages or logs are produced

### Steps to reproduce
Create a simple form with workflow that includes a single recipient for the email to be sent to. 
Move the website to another physical server
Fill in the form on the website and submit it

### Expected result

One Email 

### Actual result

Up to 4 Emails are sent out.

**Comment by nul800sebastiaan** [comment]
Hey there @rogermal - you're working with some pretty old versions there! I can not find any info about this being a problem in older versions and I do know for sure that it's not a problem in the latest versions. 

It really sounds like there's something wrong in your setup that is causing this problem, especially since you say that you can only make it happen by moving the site to the server.. 

I would encourage you to:
1. Ask around on the forums at https://our.umbraco.com to see if anyone has had this problem before, I can't really find anything that sounds like it, the closest I found related to Contour, the predecessor for Forms and that was a duplicate macro on the page.
2. Consider upgrading to more recent versions of Umbraco and Forms, a lot has changed, a lot has improved and you'll see a lot fewer bugs around.

To make sure, I tested the combo you list: Umbraco 7.7.13 and Forms 6.0.6 and it sends one email, as expected.
![image](https://user-images.githubusercontent.com/304656/75349180-8f489180-58a4-11ea-8655-5e1d58b8417b.png)
