### ISSUE TITLE
Option to limit files FileUpload can accept

### ISSUE THREAD

**Issue by cleversolutions** [umbraco/Umbraco.Forms.Issues#293]
Umbraco Forms is awesome! What would make it more awesome is if we could limit what mimetypes FileUpload would accept. When adding a File upload field to a form, in the settings it would be nice to have a text box where if left blank all files types would be accepted, otherwise you can provide a comma delimited list of allowed mime types. Then the input type=file control would render an appropriate accept attribute, and the server side code would validate each uploaded file's mime type.  

I would be happy to submit a PR, but I don't think Forms is OS. 

Thanks,
Evan

**Comment by nul800sebastiaan** [comment]
Hi @cleversolutions, not OSS unfortunately and we don't have plans to add this as a feature at the moment. However we like this idea and it's something to look into in the future when we do some more work around fieldtypes. 

For now, however, you're not stuck, you can implement your own custom fieldtype that does just this. Custom fieldtypes are documented here: https://our.umbraco.com/documentation/Add-ons/umbracoforms/developer/extending/adding-a-fieldtype

**Comment by nul800sebastiaan** [comment]
Even better, @cleversolutions - someone has already beaten you to it! Perplex has released a package with the exact feature you're asking forL https://our.umbraco.com/packages/backoffice-extensions/umbraco-forms-on-perplex-steroids/

**Comment by cleversolutions** [comment]
Awesome, thanks for the pointer @nul800sebastiaan, I'll check it out.

**Comment by nul800sebastiaan** [comment]
As of v8.5.4 you'll be able to select which file extensions are allowed on the file upload type.

**Comment by cleversolutions** [comment]
Fantastic! Thanks @nul800sebastiaan!! Replacing the file upload control in Forms with a custom one was on my list of things to do. Now I won't have to.

**Comment by konius** [comment]
Hi, @nul800sebastiaan I just had a look at the implementation and the partial view has nothing rendering to restrict file picker to those types. Additionally if forms are still stored as JSON it stores "true", "false" string values instead of bool in JSON. 

Is that a finished feature?

![Screenshot 2020-10-28 183223](https://user-images.githubusercontent.com/3933562/97466701-124a4c00-194c-11eb-8b61-bb0f364d1f45.jpg)

**Comment by nul800sebastiaan** [comment]
@konius What have you tried? The upload field will need configuration for validation to kick in 

![image](https://user-images.githubusercontent.com/304656/97471835-6bfd4700-1949-11eb-9e30-18f0e9e56f95.png)

![image](https://user-images.githubusercontent.com/304656/97471841-6d2e7400-1949-11eb-80b9-67aa2b458db0.png)

**Comment by nul800sebastiaan** [comment]
@konius What have you tried? The upload field will need configuration for validation to kick in 

![image](https://user-images.githubusercontent.com/304656/97471883-7d465380-1949-11eb-840f-506c4cbd419a.png)


![image](https://user-images.githubusercontent.com/304656/97471841-6d2e7400-1949-11eb-80b9-67aa2b458db0.png)

**Comment by konius** [comment]
@nul800sebastiaan Apologies, didn't explain myself.

1. The file configuration and "allowed types" are not rendered in the actual input partial (FieldType.FileUpload.cshtml) so it allows to pick any file https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file
2. No client side validation (need submit a form to see that you picked a wrong format)
3. When the form is stored instead of using `true`, `false,` the value stored is `"true"` or `"false"` which is a string, when  it can be Boolean type

**Comment by nul800sebastiaan** [comment]
Correct, that's how it works for now 😃 obviously we'll have to improve it in the future, but for now we at least have a way to limit the file types.
