### ISSUE TITLE
"Approve" shows for Forms without Manual Post Moderation

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco.Forms.Issues#304]
I have a form with "Enable Post Moderation" set to False,

1. In Configure Workflow
![image](https://user-images.githubusercontent.com/1782524/76425888-8aa6d180-63aa-11ea-9d6f-acd52182469b.png)

But still, when editing the Workflows for this Form the editor gets to setup workflows for "Approved":

![image](https://user-images.githubusercontent.com/1782524/76425866-84185a00-63aa-11ea-89d2-88540f223ada.png)

2. When looking at "Entries"
Same thing when looking at Entires for this form the editor can "Approve" it even though this is disabled:

![image](https://user-images.githubusercontent.com/1782524/76426039-cd68a980-63aa-11ea-91b1-c00fb24b27bf.png)

I guess that you need to look at the form.manualApproval-property in these view's to know if it should be hidden or not.

Some solutions:
1. 
In workflows-overview.html, change 
```html
<div class="umb-forms-workflows">
```
to
```html
<div class="umb-forms-workflows" ng-if="model.manualApproval">
```

2. 
Remove Approved from the response from /umbraco/backoffice/UmbracoForms/Record/GetRecordSetActions if the form does not have Manual Post Moderation set to true.

Another thing here: Should probably not show the "approve"-button if the selected entry is already approved I guess - but I can see that this would be complicated as some selected entries might be approved while others not.

**Comment by nul800sebastiaan** [comment]
Seems like an oversight :-) Doesn't hurt much, though it might be a bit confusing. 

We'll put it on the list of things to fix in the future!

**Comment by AndyButland** [comment]
Hi @enkelmedia - have been looking into this issue, and whilst it should be fairly easily resolved, I think there may be scenarios that mean we're better off leaving it as is.

In particularly due to the fact that a form may change it's setting for whether manual approval is required after entries have already been received.  So for example you could have:

- A form that requires approval
- One entry received that's not yet approved
- You change the form to automatic approval
- You then can't approve the submitted record (if we were to remove the option on the "entries" screen)

For the workflows screen, similarly perhaps people might toggle a form between manual and automatic approval, but have workflows to run "on approval" whenever it happens - so it may not make sense to hide what is configured here.

In most cases these scenarios likely won't occur and it would make sense to make these changes for automatically approved forms, but seems we do have some cases where it's better to retain them.

Can you let us know your thoughts please?

**Comment by enkelmedia** [comment]
Hi!

I follow your theoretical examples but it really feels like egde-cases and I can't see where one would toggle bach furth between manual approve or not? One approach would be to show the buttons when manual approve is active and hide en inactive. In this case the user would have to switch back to approve a entry.

**Comment by AndyButland** [comment]
Thanks for getting back - and yes, I take your point.  My worry was that by making this change we introduce the impossibility of doing something in an edge case scenario, in order to provide a small benefit in normal use (i.e. arguably avoiding something significanly worse for a few is more important than a small improvement for the majority).

But as you say, anyone in the edge case scenario can just toggle temporarily back.  And hiding the "On approve" workflows could perhaps just happen so long as there aren't any already defined.

OK... I'm convinced, I'll suggest this goes back on the to do list.

**Comment by warrenbuckley** [comment]
Fixed in PR https://github.com/umbraco/Forms/pull/430
Due for release in 8.7.0
