### ISSUE TITLE
umbracoFormLoaded event is never fired when umbracoFormsCollection is undefined

### ISSUE THREAD

**Issue by OlePc** [umbraco/Umbraco.Forms.Issues#311]
We have a setup that requires us to move the inline scripts in the form into the bottom of our masterpage. This means that `umbracoFormsCollection` does not exist until after the form is rendered. `umbracoforms.js` handles this by adding an event listener for the event "umbracoFormLoaded". But it seems like it's never executed.

Reproduction
------------
### Specifics

Where applicable:
* Umbraco version 8.5.5
* Umbraco Forms version 8.3.2

### Steps to reproduce

* In the Script.cshtml file in your theme, warp the code inside the script tag setting `umbracoFormsCollection` in a setTimeout function, and set the timeout to 5000ms.
* Set a breakpoint in the init function in `umbracoforms.js` on line 31
* Load the page with the form
* Notice that the init function is never hit

### Expected result

* When the `umbracoFormsCollection` is not available on load, the event `umbracoFormLoaded` should be executed when the form is done loading according to the comment in the `umbracoforms.js` file: "This will occur if this js file is loaded before the inline scripts, in which case. We'll listen for the inline scripts to execute a custom event."

### Actual result
* The event is never executed, so the form does not work properly.

**Comment by nul800sebastiaan** [comment]
Hi @OlePc - thanks for the research so far! Can you describe what you're actually trying to do and why? I am not sure I understand what you're doing.. :-)

**Comment by OlePc** [comment]
Hi @nul800sebastiaan let me try to elaborate.

We have a setup that requires us to make sure app <script> tags are loaded at the bottom of the page. In `scripts.cshtml` there's a script tag that we need to load later. We have a fix for this, but there seems to be some timing issues in when Forms expect to have access to the content inside this script tag. But it looks like you have a scenario for this:

See this from `umbracoforms.js`:
![image](https://user-images.githubusercontent.com/8521882/78338728-9776a980-7593-11ea-8fbd-c7e11af82b0c.png)

If umbracoFormsCollection is undefined, an eventlistener is added. But it seems like the event it's listening for is never raised.

**Comment by OlePc** [comment]
@nul800sebastiaan Any news on this?

**Comment by rutgerflohil** [comment]
@OlePc Have you checked if umbracoFormsCollection is initialized correctly? I just ran into the same problem, where the following inline script tag (Script.cshtml) was being blocked by the CSP:

`<script>
    if (typeof umbracoFormsCollection === 'undefined') var umbracoFormsCollection = [];
    umbracoFormsCollection.push('@Html.Raw(Uri.EscapeUriString(JsonConvert.SerializeObject(formJsObj)))');
</script>`

This resulted in the event never being fired and forms regex validation not working.

**Comment by Sven883** [comment]
Hey @OlePc , we're having the same issue. Did you find any solution for this?

**Comment by nul800sebastiaan** [comment]
@Sven883 @OlePc - I would really like to know how to reproduce this problem, if we can get you to post an example template which can display the problem then that would be great.

**Comment by liekeheijne** [comment]
@nul800sebastiaan I have the same problem as mentioned above. I am using vue in our site so we need to exclude the script in order for it to work. When we set exclude scripts to 0. And add the script tag for the forms at the bottom of the body tag. 
We have to do this in order for vue to keep working.

However, when we do this `typeof UmbracoFormsCollection` is `undefined` (as it should). Because it is undefined it should listen to `UmbracoFormLoaded ` event listener. 
The problem is that the event listener `UmbracoFormLoaded ` is never fired. So the form will never go to the init function.

Hope you can fix this because this is a major problom in our site now.

**Comment by nul800sebastiaan** [comment]
@liekeheijne 

> We have to do this in order for vue to keep working.

I would like to know more about this, why would Vue not work when you include the Forms scripts?

**Comment by liekeheijne** [comment]
@nul800sebastiaan because vue gives an error when you load scripts inside the div where vue is declared to. In our case, that is the div aboce the main tag. So basically the whole site is contained in that div.

The script tag to include umbraco forms should be (like all script tags) at the end of the body, outisde our div that links vue to our website

**Comment by nul800sebastiaan** [comment]
What is the error that Vue gives?

**Comment by liekeheijne** [comment]
@nul800sebastiaan 

 [Vue warn]: Error compiling template:
Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <script>, as they will not be parsed.

**Comment by nul800sebastiaan** [comment]
Thanks @liekeheijne that is actually very helpful! I don't think we can avoid using scripts in the middle of the HTML for now, but we can certainly be better at adding the `type` attribute to those scripts, as described in https://stackoverflow.com/a/51109131/5018

This should make Forms conditions (and also recaptcha and datepicker) work in combination with Vue and probably other frameworks that don't like `<script>` just being rendered in the middle of the HTML. 

I'm going to make a build of the fixes, after which you can try it with `IncludeScripts` set to `1`/`true` on your macros (this is important).

Here's a nightly build of the upcoming 8.7.5 build (I haven't bumped the version, so it will still say 8.7.4) - I tested this on an example site and it worked, but please do try this @liekeheijne @Sven883:  [UmbracoForms.Files.8.7.4.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/6707913/UmbracoForms.Files.8.7.4.zip)


Make sure to copy all the files from this zip into your local test site, overwriting everything. Afterwards, make sure to change the version number in `~\Config\ClientDependency.config` (just make it one higher) to make sure the client side cache for the backoffice gets refreshed.

⚠ If you have custom themes in the `~\Views\Partials\Forms\Themes` folder of your site (so any folder that is not `bootstrap3-horizontal` or `default`) then also make sure to update any `<script` tag there, add ` type="application/javascript"` to it, otherwise it won't work.

**Comment by nul800sebastiaan** [comment]
Whoops @liekeheijne @Sven883 note that I posted the wrong file before, the new files I've now linked to should work! Sorry if you already downloaded the previous one! https://github.com/umbraco/Umbraco.Forms.Issues/files/6708005/UmbracoForms.Files.8.7.4_2.zip

**Comment by nul800sebastiaan** [comment]
On a side note: overwriting all files will also cause `<setting key="StoreUmbracoFormsInDb" value="True" />` to change to `<setting key="StoreUmbracoFormsInDb" value="False" />` in `App_Plugins\UmbracoForms\UmbracoForms.config` and you wouldn't want to change that so please note which forms storage you used before, always keep `FormsInDb` set to `True` if it was `True` before.

**Comment by Sven883** [comment]
Hey @nul800sebastiaan - I've added all the files to our current project. The conditional logic is not working if i'm using excludescripts = 1. BUT It is working if i'm using excludeScripts = 0.

**Comment by nul800sebastiaan** [comment]
Ah yes, that's what I meant when I said to set IncludeScripts to true, forgot the setting was called the opposite.🙈

**Comment by Sven883** [comment]
@nul800sebastiaan - Ok :-) I guess our problem is solved now. Thank you for the quick response!

**Comment by liekeheijne** [comment]
@nul800sebastiaan thans for the help!

**Comment by nul800sebastiaan** [comment]
Good news! Not sure when we can get 8.7.5 our but hopefully we should have some news about that next week,

**Comment by Sven883** [comment]
Hey @nul800sebastiaan  - Any idea if the release of v8.7.5 is still planned for this week? Thanks!

**Comment by AndyButland** [comment]
Have just finished the preparation for the release, it will be out on Tuesday July 6th.
