### ISSUE TITLE
Invalid ID in fieldset (sometimes)

### ISSUE THREAD

**Issue by jacklawry** [umbraco/Umbraco.Forms.Issues#316]
A brief description of the issue goes here.

In the default Form.cshtml file it uses `id="@fs.Id"` this is fine except when the guid it generates starts with a number 0-9 instead of a letter a-z.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Specifics

I am using v7.3.1

### Steps to reproduce

Create a new form and add various groups
Check the groups on the frontend and eventually you will have an id that starts with a number

### Expected result

All ID numbers should start with a letter or you can't style them with css

### Actual result

Some ID start with a number 

Suggest adding "fieldset_" to the start of the ID e.g. `id="fieldset_@fs.Id"` so the id is always valid even if it stars with a number.

**Comment by nul800sebastiaan** [comment]
Thanks @jacklawry, unfortunately that would be a breaking change for people relying on this being a guid. We always need to be super careful when we change what we render because people have built all kinds of assumptions around the output they have been getting so far.

I guess I know the answer to this one, but.. any chance you're using HTML4? Since HTML5 is very permissive in what the id can be (basically any character, as long as it's more than 1 char): https://stackoverflow.com/a/79022/5018

**Comment by jacklawry** [comment]
No I am using html 5 but some browsers don’t work with an ID starting with a number. But don’t worry. I have added the guid as a class for now and am using this. 

Thanks,
Jack

**Comment by ronaldbarendse** [comment]
The biggest problem is targeting the element in CSS, as IDs starting with a digit aren't valid identifiers: https://www.w3.org/TR/CSS21/syndata.html#characters

> In CSS, identifiers (including element names, classes, and IDs in selectors) can contain only the characters [a-zA-Z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_); they cannot start with a digit, two hyphens, or a hyphen followed by a digit. Identifiers can also contain escaped characters and any ISO 10646 character as a numeric code (see next item). For instance, the identifier "B&W?" may be written as "B\&W\?" or "B\26 W\3F".

**Comment by nul800sebastiaan** [comment]
Be that as it may, if this is a problem, make sure to use a different css selector or make a theme where you can make adjustments to this one. Make sure NOT to update the default theme since it will be overwritten when you upgrade forms. 

As explained before, people rely on this behavior now and we don't want to introduce a breaking change for this.
