### ISSUE TITLE
Magic strings, Session & Cookies not working

### ISSUE THREAD

**Issue by hkooikerspeak** [umbraco/Umbraco.Forms.Issues#320]
When using magic strings from session & cookies, the placeholder is not being parsed.

Reproduction
------------

### Bug summary

The ParsePlaceholder function is never executing the ParseContextPlaceholders function. Only by the ExecuteWorkflows function but never on the front-end.

### Specifics

Umbraco Forms 8.4

### Steps to reproduce

Create a form with a form field Title & Description.
Use for example [%SomeSessionValue] in the description.

### Expected result

I expect the placeholder being parsed to the session value.

### Actual result

The placeholder is not being parsed.

---
_This item has been added to our backlog [AB#6174](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/6174)_

**Comment by nul800sebastiaan** [comment]
Hi @hkooikerspeak - we'll be looking at this in the near future, it might be related to fixes we did in #120, but we're not sure yet, needs investigating. We'll get back to you when we know more!

**Comment by jeannieSoS** [comment]
I've set up a form embedded on a template so that users can create a node and the form appears. The form passed the pageID and pageTitle using magic strings [#pageID] [#pageTitle]. I could then pull back the responses by pageID and display them on the page. Upgrading to Umbraco 8.6 and Forms 8.4 has broken the form. The magic strings don't work and the display of responses is also inconsistent. Sometimes the comment, name and date appear, sometimes just the name and date and so on.

**Comment by nul800sebastiaan** [comment]
@jeannieSoS Many apologies for breaking your install! We're getting close to a fix for v8, make sure to follow along on the following issue: https://github.com/umbraco/Umbraco.Forms.Issues/issues/321

@hkooikerspeak I'll close this one as a duplicate, the fix for this will be available when we finish https://github.com/umbraco/Umbraco.Forms.Issues/issues/321 - thanks for reporting!
