### ISSUE TITLE
Copy form groups

### ISSUE THREAD

**Issue by TimGeyssens** [umbraco/Umbraco.Forms.Issues#324]
Would be nice if you could copy form groups...

**Comment by nul800sebastiaan** [comment]
Thanks, I am not sure what this means, can you explain a use case and who this would help, how does it help?

**Comment by TimGeyssens** [comment]
Sure, you can make groups in the form right? And then you can add fields to this group? But what if you need to add x groups with the same fields, like in this example:

![Untitled](https://user-images.githubusercontent.com/2988648/78669867-332e4f80-78dd-11ea-9f31-dc3c47a94c87.jpg)

I have a repeating number of groups with the same fields... adding this 10 times is a drag... so copy option in editor would be nice :)

**Comment by nul800sebastiaan** [comment]
Wouldn't it it then be better, as you suggested in https://github.com/umbraco/Umbraco.Forms.Issues/issues/325 to have a whole group to be repeatable?

This looks like "webshop functionality" which is not really what Forms would be the best use for in my opinion.

Of course currently you know you could edit the Forms definitions on disk to do this a bit quicker than entering each field 10 times through the interface.

There may be other good use cases that I am not aware of but it seems pretty rare to me that you'd want to repeat a bunch of fields many times. 

Anyway, we'll have a chat about it with the product owner and get back to you. Note: this will take a while due to Easter holidays.

**Comment by TimGeyssens** [comment]
Sure, but I think the copy option will be easier to implement then the repeatable stuff :)

**Comment by warrenbuckley** [comment]
Fixed in PR https://github.com/umbraco/Forms/pull/442
Due for release in 8.7.0
