### ISSUE TITLE
Missing information in FormsHtmlModel

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco.Forms.Issues#33]
The FormsHtmlModel used in Razor email template workflow is missing critical information for reusing the template for all the forms in a site.

I would suggest to add at least the name or id of the form to be able to switch some content in the template (e.g.  Thanks for contacting us / Thanks for your quote request / etc)

Maybe we even need a title input or a introtext textarea to give the editor the power to customize the email for every form where needed.

**Comment by bergmania** [comment]
I have added a PR that include the `FormId `to the `FormsHtmlModel `. 

If you need more information, I suggest you add that in hidden fields for the form.

**Comment by bergmania** [comment]
@sussexrick, we can provide the unique id (guid). When the emails are sent where is not generated a int-id yet.

**Comment by sussexrick** [comment]
@bergmania GUID would be great, thank you. I imagine you'll have a long term plan to use those instead of int ids anyway, as with the main CMS?

**Comment by clausjensen** [comment]
@sussexrick Currently there's no long term plan defined for Forms yet 😄 But as with the CMS - we will most likely at some point support guids as well as ints in all the APIs.

**Comment by warrenbuckley** [comment]
Connects https://github.com/umbraco/Forms/pull/215

**Comment by tomvanenckevort** [comment]
What happened to the PR for this? The label seems to suggest it was part of 7.0.5, but that doesn't seem to be the case.
Will it be part of the next release?

**Comment by tomvanenckevort** [comment]
I can now confirm that this is part of the 7.0.6 release that was released yesterday. Thanks for adding it in, it has helped me quite a lot on my current project!

**Comment by clausjensen** [comment]
@tomvanenckevort Sorry for the lack of information. We have the problem that Forms is a closed source project so we can't actually use the github issue tracker on that repository as a public issue tracker. This means we have this "extra" issue tracker purely for the purpose of being a public issue tracker for Forms.

It however also means that we have to replicate issues over from this to our private one - and that you won't be able to automatically follow progress here due to those things not really being linked. We're trying to figure out if there's a better workflow but for now we just have to try to update this one manually when things are fixed.

**Comment by thenexus00** [comment]
Where did this get too in the end? None of this seems to work and with Umbraco 8 there has been big changes.

**Comment by clausjensen** [comment]
@thenexus00 I believe this was added in 7.0.6 as mentioned above. If you're still having trouble could you please create a new issue describing what the problem is?
