### ISSUE TITLE
Error on GetFieldTypeByField when rebuilding forms index / removing entries

### ISSUE THREAD

**Issue by Haugst3d** [umbraco/Umbraco.Forms.Issues#339]
I am running umbraco 8.4 and Umbraco Forms 8.4. I upgraded Forms from 8.2 to 8.4 as some of the issues I had seemed to be fixed in 8.3 and 8.4 (deleting form entries and building the index). However I am still experiencing problems, and I believe the root cause is the site being unable to rebuild the forms index.

<img width="1442" alt="umbraco index error" src="https://user-images.githubusercontent.com/7870045/79568837-e0ac1a80-80b6-11ea-99e3-f0e57b8727cc.png">

When I go to examine management, I am able to re-build all indexes except the one for umbraco forms. the browser Console displays an error, which points to something related to Fields and/or FieldTypes.

The index used to contain at least 24 documents which I deleted while tracing the error. After removing the index files from disk, segments.gen, segments_9 and write.lock is recreated when the application restarts.

I am unable to reproduce this in my own environment. The error occurs in my clients production environment. However I believe it might have occurred after they re-did all their existing forms, changing, removing, adding, renaming multiple fields

**Comment by nul800sebastiaan** [comment]
That's a new error, I haven't seen that before. I assume you must have had the same error and problem in Forms 8.2? 

I can only recommend you contact the support channel to get this checked out, the best way to help you would be if you could send a copy of your database over plus the forms definitions you have in `App_Data\UmbracoForms\Data`. Something with a FieldType is null but it's not possible to see from that error what exactly it is.

When you're logged into your profile on umbraco.com you should be able to go to https://shop.umbraco.com/profile/options/get-help-and-support/forms-support-download/ to fill in the support form.

**Comment by nul800sebastiaan** [comment]
Looks like I closed this one prematurely, sorry about that! 

From looking at the code I can see that the fix for #305 somehow never made it into the final build of 8.4.0. 😬 

I've re-applied the code that should have been there now and from version 8.4.1 it should work.

Could you and/or @enkelmedia or @timmywiff give this build a go? Dropping the dlls from the attached file into your bin folder should be enough to test if it works now.

[UmbracoForms.Files.8.4.1-alpha.20200423.2.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/4521147/UmbracoForms.Files.8.4.1-alpha.20200423.2.zip)

Apologies for the inconvenience, not sure what happened here!

**Comment by enkelmedia** [comment]
@nul800sebastiaan Just gave this a test-spin and it seems to work fine =D 

What I did:
* Created new Form with two fields
* Posted the form to add new entry with value for both fields
* Remove one field from the form
* Removed the entry from the "Entries"-list.

That worked!
