### ISSUE TITLE
The Submit button "title" is hard-coded to "Send Email"

### ISSUE THREAD

**Issue by craigs100** [umbraco/Umbraco.Forms.Issues#359]
A brief description of the issue goes here.

The Submit button "title" is hard-coded to "Send Email".

Reproduction
------------

### Bug summary

The Submit button "title" cannot be changed in the UI. It's on Form.cshtml line 113.

### Specifics

Form.cshtml line 113:-
`<input type="submit" class="btn btn-primary" value="@Model.SubmitCaption" name="submitbtn" title="Send Email" />`
Note the title is hard-coded. An interim measure would be to change it to:-
`<input type="submit" class="btn btn-primary" value="@Model.SubmitCaption" name="submitbtn" title="@Model.SubmitCaption" />`
Ideally it should have it's own setting in the UI, as the label does.

### Steps to reproduce

Create any Form and have it display on a page and mouseover the Submit button.

### Expected result

I would like to be see the mouseover tooltip display text set by the user. Particularly important in a multi-lingual site.

### Actual result

The mouseover tooltip displays "Send Email".

**Comment by nul800sebastiaan** [comment]
Hey there @craigs100 - we don't ship with any title attribute on this button at the moment, maybe we did in the past, I'm not sure about that.

What would the value be of being able to configure the title attribute separately? I am having a hard time imagining what you'd want to put in the title attribute that isn't already conveyed in the name attribute.

The reason I'm asking is: yes, it's possible to make this configurable by the user, but does the user actually know what the difference is between the button name and the button title? I'm afraid that they will be more confused than helped by having an additional three fields to consider filling in (since Previous and Next buttons should then also offer the same behavior).

**Comment by craigs100** [comment]
Hi @nul800sebastiaan. You're absolutely right. The default and bootstrap versions don't have the line in that I was bothered about! The Form.cshtml that I'm using in my theme was, I thought, a copy of the default one with minor changes. Maybe it was taken from an earlier version. Anyway we can close this issue now. Whether there "should" be a title attribute though, I would leave for the Accessibility Team. I might ask them on Slack ;)
