### ISSUE TITLE
Prevalue sources "List grand children" not finding grand children

### ISSUE THREAD

**Issue by shearer3000** [umbraco/Umbraco.Forms.Issues#365]
This issue is being reported for both UmbracoForms 8.4.0 and 8.4.1

We have a prevalue source configured as type “Umbraco Documents”
![image](https://user-images.githubusercontent.com/2433680/83713053-3e062600-a67b-11ea-8f69-aeddf2e0083e.png)

And the "List grand children" tickbox is selected:
![image](https://user-images.githubusercontent.com/2433680/83713092-537b5000-a67b-11ea-8041-ecfebdf84c14.png)

When the “root node” id specified is a grandparent of the “Document type” nodes (i.e. 2 or more levels above) then no matching items are listed. 
![image](https://user-images.githubusercontent.com/2433680/83713161-80c7fe00-a67b-11ea-82dd-20803ffd1454.png)

However, if the “root node” id specified is a parent of the “Document type” nodes (i.e. 1 level above) then matching items are listed.
![image](https://user-images.githubusercontent.com/2433680/83713212-a05f2680-a67b-11ea-82ec-3ec76b6f5479.png)

**Expected Results:** "List grand children" means nodes from any level below “root node” are found
**Actual results:** only nodes immediately below “root node” are found ("List grand children" not working)

---
_This item has been added to our backlog [AB#13031](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/13031)_

**Comment by nul800sebastiaan** [comment]
Hi @shearer3000, can you clarify what this means?

> When the “root node” id specified is a grandparent of the “Document type” nodes (i.e. 2 or more levels above) then no matching items are listed.

Or even better can you send a full screenshot of the configuration that works/doesn't work?

**Comment by nul800sebastiaan** [comment]
I guess I also need to understand what your tree structure looks like?

**Comment by shearer3000** [comment]
Hi Sebastiaan, I hoped my post would be easier to understand - basically, if the Id you specify as the root node is two or more levels above the items you expect to appear as the list of nodes then nothing actually shows. 
Yep I can post more screenshots in the morning 🙂

**Comment by shearer3000** [comment]
here is the tree structure
![image](https://user-images.githubusercontent.com/2433680/83837716-3f9f1f00-a74b-11ea-8b0c-aeefee871289.png)

if the "products" node id (1344) is used for the prevalue source "root node" then nothing is listed. 
![image](https://user-images.githubusercontent.com/2433680/83837805-960c5d80-a74b-11ea-821f-1b59fef920b2.png)

However, if the "tubs" node id (1423) i used then the children below this are listed.
![image](https://user-images.githubusercontent.com/2433680/83837850-b0463b80-a74b-11ea-95ba-89fd1ed8635c.png)

**Comment by Myster** [comment]
Aside: I think "All Descendants" is a better term than "Grandchildren" since grandchildren are technically only children's children and no more or less.

**Comment by ronaldbarendse** [comment]
I'm having the same issue and agree with @Myster about the naming: it should switch between only children (off) and all descendants (on).

After doing some more testing, it looks like it only gets the descendants when the children are also of the specified document type (e.g. have the root node set to the catalog and document type to Catagory will get all levels if the structure is Category > Category, but not when it's MainCategory > Category).

It's also not possible to specify multiple root nodes (e.g. get to products with a specific parent node type) or just use a single XPath query to get all documents to use as pre values.

**Comment by dannydrogt** [comment]
@nul800sebastiaan any progress on this? I happened to run into this same issue today. Also, it feels like a small fix, but a pretty common use case.

**Comment by AndyButland** [comment]
Could you update on what issue you are finding with the current version please @dannydrogt?  I've just tried to replicate on the latest V8 and find:

- The label "grandchildren" is still present and would be better labelled as "descendents"
- I get a duplicate prevalue rendered when including grand-children or lower levels.

But otherwise it seems to work... e.g. with this structure.

![image](https://user-images.githubusercontent.com/1993459/126657179-117ffc6d-2b58-4d98-b57d-eb0f9434a738.png)

I'm seeing this (with the duplicate bug fixed):

![image](https://user-images.githubusercontent.com/1993459/126657311-c29744a5-e578-44e9-8649-e3ca28aa2135.png)

Could you let me know if I'm missing something else that we could have a look at please?  It might be a case as you say of fixing the simple bugs, but then look also at re-implementing as I'm not convinced it's particularly efficient as is, especially if you weren't very careful about ensuring there aren't too many descendent nodes.

**Comment by dannydrogt** [comment]
Hi @AndyButland,

The difference with your setup is that all the descendent nodes are the same Doctype; in that case, this works.
My tree is setup like this (can't share a screenshot for the specific case because of NDA reasons):

Doctype A
- Doctype B
-- Doctype C
-- Doctype C
-- Doctype C
- Doctype B
-- Doctype C
-- Doctype C

Root node is set to item with Doctype A (either through picking it, or an XPath that evaluates to it), "Document Type" in the dropdown is set to "Doctype C".

This won't show any prevalues, because **NodePreValues.GetPreValues()** and **NodePreValues.LoopChildren()** both only traverse child-items when the parent is also actually of the chosen Document type. 
A quick look with DotPeek showed this;

`if (!(pagedChild.ContentType.Alias != this.DocType))`

So I'm not sure if this is just how this was supposed to work, but I think the content-tree I described here is kind of a pretty common one and I think it would be a good addition if NodePreValues were to support this.

Let me know if you need anything else!

**Comment by AndyButland** [comment]
Thanks @dannydrogt - understood, and yes, agreed.  I'll look at fixing up the following for the next release:

- Omit doc types that don't match the alias, but continuing looking for descendants under them.
- Fix up the duplicate value that appears in lower levels
- Change the label to "List all descendants"
- Add the ability to choose the order - either "Node order" (the default and current behaviour) or "Alphabetical", as that might be useful when going below the children of the selected node.
- Made the selection of the root node optional when you also select "Use current page as root".

**Comment by dannydrogt** [comment]
Sounds great @AndyButland thanks! #h5yr

**Comment by warrenbuckley** [comment]
Fixed in this PR
https://github.com/umbraco/Forms/pull/554

Due for release in 8.8.0
