### ISSUE TITLE
IRecordReaderService returns Records with empty RecordFields 

### ISSUE THREAD

**Issue by Szpi** [umbraco/Umbraco.Forms.Issues#372]
IRecordReaderService.GetRecordsFromForm returns Records with empty RecordFields, but in database everything seems alright and on backoffice everything is displayed as expected.

Unfortunately I don't know steps to reproduce this issue. Rebuilding examine indexes does not help.

Is there any service that provides similar information and it is based on database instead of examine?

We are using Umbraco.Forms 8.4.1

**Comment by nul800sebastiaan** [comment]
I think you want `RecordStorage.GetRecords` and set the `includeFields` boolean to `true`. Probably best to do a combination of `GetRecordsFromForm` and and `GetRecords`, if you have many records, you want to do some paging there.

**Comment by Szpi** [comment]
I have tried to call GetAllRecords, but still get empty results in RecordsFields. Do you have idea why?
![image](https://user-images.githubusercontent.com/23508122/86580819-8321be80-bf7f-11ea-9ac3-bc7caf8eb9d0.png)

**Comment by nul800sebastiaan** [comment]
Is that your actual RecordData? Looks hashed.. ?

`GetRecords` (maybe don't do `GetAllRecords`, it will get everything) goes straight to the database.. so I am not sure what could be going on, but if you're changing the data that gets stored (looks like it) then Forms has no chance of giving you back the correct data since it doesn't know what it used to be.

**Comment by Szpi** [comment]
It is RecordData from our test environment and unfortunately I need to get every record.
