### ISSUE TITLE
duplicate form exception

### ISSUE THREAD

**Issue by tom-activeis** [umbraco/Umbraco.Forms.Issues#425]
server error when saving a form that has a duplicate name 

Message: "An error has occurred."
StackTrace: "   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
↵   at Umbraco.Forms.Web.Editors.FormController.FormExist(String formName)
↵   at Umbraco.Forms.Web.Editors.FormController.SaveForm(FormDesign formData)

### Specifics

Umbraco forms version 8.5.3

### Steps to reproduce

1. copy an existing form
2. rename it to remove the appended "(1)" so has same name as existing form
3. form is renamed (form gets saved with duplicate name)
4. form cannot be modified or saved any further (e.g. adding fields)

### Expected result

form gets saved OR should be unable to save form on step 3 on duplicate name

### Actual result

server error on form save

---
_This item has been added to our backlog [AB#9084](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/9084)_

**Comment by ronaldbarendse** [comment]
If the forms are stored in the database, this might be related to https://github.com/umbraco/Umbraco.Forms.Issues/issues/402.

**Comment by tom-activeis** [comment]
ah, we're not storing forms in database in this project

it looks as though there might be validation to prevent forms of the same name being created, but this must be being bypassed when the form is copied and renamed, as in the steps to reproduce supplied

**Comment by AndyButland** [comment]
In looking to resolve this today, I couldn't replicate - so seems it has been resolved at some point since the issue was raised.

I've tested with forms configured for storage on disk and in the database, and in both cases if I copy a form and enter the name of the current or another existing form, the name is suffixed with " (1)" or similar to ensure form names are unique.

I'll close tag as part of the latest release though was likely fixed in an earlier version.
