### ISSUE TITLE
Feature request - ReCaptcha v3 on Forms

### ISSUE THREAD

**Issue by Jay-umbr** [umbraco/Umbraco.Forms.Issues#455]
Forms still use v2, isn't it time to update?
https://developers.google.com/recaptcha/docs/v3

---
_This item has been added to our backlog [AB#9979](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/9979)_

**Comment by c9mbundy** [comment]
YES! - This is needed for both Forms-7 as well as Forms-8

Google has acknowledged ReCaptcha-v2 is vulnerable to spambot attacks, but are disinterested in fixing the problem, despite its widespread use on the web. Their recommended solution is moving to ReCaptcha-v3

I have a number of clients on Umbraco-Cloud-7 who are now being hammered by this, and UC-7 (and hence Umbraco-Forms-7) will be around quite a while to come, so ignoring the problem should not be considered an option, but given priority due to the problems and risks that clients are now exposed to with spambots bypassing ReCaptcha-v2 and no ReCaptcha-v3 option being available to counter it.

I would have thought most of this should be a copy/paste and tweak, but Umbraco-Forms code is always seems more complex than that.

**Comment by MichaelNielsenDK** [comment]
Also seeing issues with bots circumventing ReCaptcha 2, so an upgrade to v3 is really needed and strongly recommended by Google.

**Comment by c9mbundy** [comment]
Bump - some feedback on this would be appreciated.

Our Umbraco-Cloud-7 sites are being hit by bots bypassing ReCaptcha-v2 and there is no option available for implementing the Google recommended solution of replacing it with ReCaptcha-v3. Clients are complaining to us that they are paying for a service but being ignored when it comes to a problem with a basic requirement - and we don't know what to tell them at the moment.

**Comment by MichaelNielsenDK** [comment]
I've been in contact with Umbraco Support, and the answer is, they refer to the answer here
https://github.com/umbraco/Umbraco.Forms.Issues/issues/446#issuecomment-724833350  
and will not prioritize it further. 🤷‍♂️

**Comment by c9mbundy** [comment]
That's very disappointing, as that response obviously does nothing to address the problem of v7. The comments from my clients are that they are paying a license for Umbraco-Forms (in their case as part of the ongoing Umbraco-Cloud fee) and expect better than being ignored when it comes to such a major forms issue as effective spam-control.

**Comment by nul800sebastiaan** [comment]
I hear the feedback and understand it's frustrating. 

A few things to note here:

Recaptcha3 works fundamentally differently from v2 - it is completely invisible and requires the implementor to take action based on the recaptcha score: https://developers.google.com/recaptcha/docs/v3#interpreting_the_score
They recommend not accepting submissions with a score of 0.5 of lower. We could implement that, but the risk is that we reject too much. Additionally, there is no way to give the form submitter an option to prove that they're not a bot, there's no fallback. 

The safest way to deal with this will require a more complicated flow: we can accept all submissions but not approve records with a score of <= 0.5. This will require you to set up or change your workflows accordingly and to enable post moderation on each of these types of forms. This might be an okay trade-off? It will definitely require some documentation on how to set everything up correctly since it's not intuitive and we no longer are able to do it "just" in a simple field.

For now, the alternatives are:
- uCaptcha, which uses hCaptcha https://our.umbraco.com/packages/website-utilities/umbracoformsucaptcha/
- Some custom code based on https://our.umbraco.com/packages/website-utilities/recaptcha-v3-for-umbraco-forms/ - turns out this plugin doesn't do rejection. Additionally, it should also hide the recaptcha field from the frontend, as there's no way to interact with it (right now it just shows an input of type text).

As for v7, the way of writing custom fields has hardly changed and porting the code over for the Recaptcha v3 plugin shouldn't be too problematic (in fact, looks like the only necessary change is to change `Current.Logger.Warn` to `LogHelper.Warn`).

**Comment by c9mbundy** [comment]
I appreciate the response, and not wanting to shoot the messenger, but one way or another, everyone pays a license-fee for Umbraco-Forms, making it a commercial product. The lack of a correct implementation of ReCaptcha-v3 is something that's long been a glaring shortcoming in both v7 & v8 - and which is now the cause of problems for users of the product - and yet what Umbraco is effectively saying in this response is that it's the customer's responsibility to fix a shortcoming in a product they are paying for.

AFAIK, Umbraco-Forms is not an open-source project, and so in the absence of a formal solution, adding ReCaptcha-v3 requires either a 3rd-party plugin that works properly (which never happened for v7) or a custom code solution - to deal with a problem that is at the heart of the very nature of a forms package.

If, for whatever reason, you are going to recommend customers custom-code their own solution, then perhaps an open-source Git project might be a better approach, so that people are not forced to reinvent the wheel as they run into this problem - which would appear likely to become an increasingly urgent issue, as Google has made it clear they have no intention of 'fixing' ReCaptcha-v2.

As for the specific implementation issues mentioned:

- Presumably a rejection score floor is something that could be parameterised in the field definition (perhaps using a slider field) so each application of the can reference their own score to approve.

- Having a 'fallback' ability to 'prove' you are not a bot would seem to make little sense in this context, as proving you are not a bot is the very reason that we are in this situation i.e. the ReCaptcha-v2 method of proving this can be broken by a bot - so what are you going to use as a better test when ReCaptcha-v3 decides the score is low? Presumably whatever you come up with would need to be better than ReCaptcha-v2. I'd suggest that if ReCaptcha-v3 says you are a bot, you probably should fail.

**Comment by nul800sebastiaan** [comment]
The situation right now is that we have a working feature (Recaptcha2) which is an implementation of a 3rd party API. It is unfortunate that the API is fundamentally broken. At this moment, we haven't been able to prioritize developing the new feature (v3) to replace the current one. However, with the description above, I am confident that with a bit of custom code, you can protect your forms for the time being until we start our work.

> Presumably a rejection score floor is something that could be parameterised in the field definition

Agreed! As per Google's Docs: https://developers.google.com/recaptcha/docs/v3#interpreting_the_score - `As reCAPTCHA v3 doesn't ever interrupt the user flow, you can first run reCAPTCHA without taking action and then decide on thresholds by looking at your traffic in the admin console. By default, you can use a threshold of 0.5.`

> Having a 'fallback' ability to 'prove' you are not a bot would seem to make little sense

This is exactly what Google tells us to do. As per Google's Docs: https://developers.google.com/recaptcha/docs/v3#interpreting_the_score - `Based on the score, you can take variable action in the context of your site.`
They recommend either throwing up a second factor auth, email verification or just identifying and seggragating risky form submissions. 

I can't tell you how many times I get to click tiles in Recaptcha 2 just because I connect to a VPN, open a private browsing window, etc. If I get detected as a bot this many times then I would hate to think how many forms submissions you would miss out on if the submission just got deleted.

This is one of the reasons why we don't "just" implement a quick recaptcha3, we need to consider what will happen and how we can help people tune their settings for it so they don't lose data.

Additionally, each verification is valid for 2 minutes, we need to consider what happens on a multi-page form that is validating on the first page but submitting all the steps takes longer than 2 minutes.

**Comment by jono-k** [comment]
I am also disappointed with the responses here, considering Umbraco Forms is a paid service. My clients are complaining about spam and asking why we can't use reCaptcha V3.

I have setup reCaptcha V3 on a client's site that uses my own custom forms, and it is working well with the default settings.

I would be happy to pay for the Umbraco Forms reCaptcha V3 add-on if required, I just need to keep my clients happy and minimise spam.

**Comment by bjarnef** [comment]
I have also seen bots bypassing reCAPTCHA v2, so it doesn't really well.
Additional I suggested in this issue a setting to blacklist specific domains sending spam `@motorza.ru` although some are spam entries from `@gmail.com` which we can't blacklist. This doesn't replace reCAPTCHA v3, but could help preventing spam.
https://github.com/umbraco/Umbraco.Forms.Issues/issues/169

**Comment by AndyButland** [comment]
Implemented in [PR 438](https://github.com/umbraco/Forms/pull/438) for release 8.7.0.

**Comment by MichaelNielsenDK** [comment]
Is it fixed for v7 also?

**Comment by c9mbundy** [comment]
> Is it fixed for v7 also?

Agree absolutely - v7 is supported on Umbraco-Cloud until 30-Sep-2023 so can't be left exposed to spam-attacks via ReCaptcha-v2 until then - it also needs ReCaptcha-v3

**Comment by AndyButland** [comment]
Hi @MichaelNielsenDK @c9mbundy - noet yet, but yes, the plan is to port this over to V7 for the next release of that version too.

**Comment by c9mbundy** [comment]
@AndyButland - that's EXCELLENT news - thanks.

**Comment by MichaelNielsenDK** [comment]
@AndyButland Awesome 🤘

**Comment by warrenbuckley** [comment]
This has been backported to V7 in this PR here
https://github.com/umbraco/Forms/pull/452

This will be due for release in 7.5.0

**Comment by c9mbundy** [comment]
@warrenbuckley - Look foward to the release of 7.5.0 and placating clients. 
FWIW, I suspect that umbraco/forms is not a public repository, as clicking the link above results in a 404 for me.
