### ISSUE TITLE
Conditions on groups are invisible

### ISSUE THREAD

**Issue by AllanKirk** [umbraco/Umbraco.Forms.Issues#471]
If I add a new group, and set some conditions, they are invisible in the gui. If I mark the invisible text to the right of the group name, I can see the text is there, it just has the same color as the background, which is unfortunate.

![image](https://user-images.githubusercontent.com/21119705/103850077-fc3dd200-50d8-11eb-9a7b-838256ea73c7.png)

Umbraco 8.10.1
Forms 8.6.0
Cloud

**Comment by nul800sebastiaan** [comment]
Thanks for the report @AllanKirk - I had a look and it seems that this could be caused by `umb-auto-resize` not working properly for some reason. Does it help to click the "Reorder" button and click it again?

Try as I might, I tried getting this reproduced but it works for me (8.10.1 on Cloud with Forms 8.6.0). Is this an upgraded install? Maybe try downloading `UmbracoForms.Files.8.6.0.zip` from https://our.umbraco.com/packages/developer-tools/umbraco-forms/ and try to compare the files in there to the files in your Cloud site, maybe something didn't upgrade correctly?

**Comment by AndyButland** [comment]
This was also spotted in issue #590, and picked up for the latest patch release, so will close and tag this one too.
