### ISSUE TITLE
Email Validation allows emails without a period in them

### ISSUE THREAD

**Issue by vishnukum-code** [umbraco/Umbraco.Forms.Issues#474]
when i try to use validation in umbraco forms the Email validation is not working properly. If i enter only tester@gmail then its not throw validation message . Mail does include something before @, something after @, a dot, and something after the dot.

**Comment by nul800sebastiaan** [comment]
Funnily enough, `tester@gmail` is a perfectly valid email address https://stackoverflow.com/questions/20573488/why-does-html5-form-validation-allow-emails-without-a-dot 
I guess we should have an option to do a stricter check as well. For now you could use a stricter regex, `([-!#-'*+/-9=?A-Z^-~]+(\.[-!#-'*+/-9=?A-Z^-~]+)*|"([]!#-[^-~ \t]|(\\[\t -~]))+")@[0-9A-Za-z]([0-9A-Za-z-]{0,61}[0-9A-Za-z])?(\.[0-9A-Za-z]([0-9A-Za-z-]{0,61}[0-9A-Za-z])?)+` seems reasonable, found it here: https://stackoverflow.com/a/14075810/5018

**Comment by PeterHuys** [comment]
Further: the standard validation strings don't have the start ^ and end $ resulting that the value is valid if the field contains a valid email adress in the middle, which can be prefixed or suffixed with anything:

![afbeelding](https://user-images.githubusercontent.com/6603304/106120570-d3987d80-6156-11eb-99d2-4535943a538d.png)

**Comment by nikolajlauridsen** [comment]
The problem with allowing emails to be prefixed and suffixed with anything as mentioned by @PeterHuys has been fixed and will be in the next release.

I'll leave the issue open though since it's marked as an idea to create a more strict email verification option

**Comment by AndyButland** [comment]
With the next minor release of Forms (10+) we are introducing a means for implementers to add or remove the validation patterns available.  So rather than just having the fixed "number", "URL" and "email", you can add further ones, and remove default ones.

Given that, I think we can now close this issue.

If it's preferred to use a different regular expression for validating emails, an implementer can now do that by removing the shipped email pattern and providing their own one.

The related issue is [936](https://github.com/umbraco/Umbraco.Forms.Issues/issues/936).
