### ISSUE TITLE
Form fields as rows not just columns

### ISSUE THREAD

**Issue by hifi-phil** [umbraco/Umbraco.Forms.Issues#555]
Is there any reason that form fields can only be ordered into columns?

I think that working with the fields as rows would be a much better solution, improving tab ordering and allow responsive stacking into how the user would expect the form to break down and order.

**Comment by nul800sebastiaan** [comment]
What about groups? Which I think render as fieldsets? Is that what you need?

![image](https://user-images.githubusercontent.com/304656/118016045-36ec9b00-b355-11eb-9fee-5ef88e0fe688.png)

**Comment by hifi-phil** [comment]
Yes, but it's hardly a clean solution. With a complex multi-row form you could end up with many fieldsets which wouldn't be great semantically.  And it limits you when you want to create a fieldset.

**Comment by nul800sebastiaan** [comment]
@hifi-phil Sorry for the late follow-up. Do you want both fieldsets and rows? I think I need an example since I am not sure what the problem is with many fieldsets and what exactly a "row" is in your mind.

**Comment by geoffbeaumont** [comment]
The problem is both semantic - the fields belong together grouped under one fieldset, but need to be presented in multiple rows - and presentational (which is sort of but not exactly the same thing) - the fields need to be presented as a group which then needs to collapse keeping horizontally adjacent fields together when on a small screen.

For example, I'm building a form at the moment which collects requirements for timings and catering requirements for an event, split into rows for access time, delegate arrival coffee, start of session, mid-morning break and so on. Each row has four fields which need to stay together. The only way to do this in Umbraco Forms is to make each row a group (fieldset), but each fieldset is presented as a card in the UI which makes this a messy solution - and in any case I need to group sets of these fields for multi-day events.

The only solution I can see with Umbraco Forms is to create each row as a group then use CSS targeting the fieldset IDs (so a truly nasty, form specific solution) to group the fieldsets visually. They'll still be semantically incorrect.

It also causes me problems with some of the custom code on this site (repeating fields), but the latter is somewhat out of scope and there are plenty of other challenges to achieving this in Umbraco Forms.
