### ISSUE TITLE
Incorrect version showing on forms page

### ISSUE THREAD

**Issue by russellshome** [umbraco/Umbraco.Forms.Issues#564]
On the forms page [URL]/umbraco#/forms

The page shows  "Current installed version of Umbraco Forms: "7.0.4"

But the installed version according to nuget is 7.5.1

Reproduction
------------

Install umbraco & make a website
Install umbraco forms 7.5.1
Put licence file in bin folder

Log in and go to the forms page in admin

Only affects Umbraco 7.

**Comment by nul800sebastiaan** [comment]
I think this is because of the way we update that version, it was a bit hacky in v7, in `App_Plugins\UmbracoForms` there's a file called `version` which contains the version that is being read into the dashboard. After updating it you probably need to recycle the application pool to see the correct version number there.
