### ISSUE TITLE
Ability to customise the message and log level when ->The g-recaptcha-response hidden field for reCAPTCHA V3 is missing and thus unable to be verified

### ISSUE THREAD

**Issue by mistyn8** [umbraco/Umbraco.Forms.Issues#573]
Ability to customise the message and log level when ->The g-recaptcha-response hidden field for reCAPTCHA V3 is missing and thus unable to be verified

We see this in the main occurs when spam bots remove or don't populate the hidden field.
I know we could also have when a real user disables javascript too, though Web2.0 how common would that be.

We were thinking INFO would be more suitable than WARN? But the ability to customise would cover all bases?

**Comment by nul800sebastiaan** [comment]
Thanks @mistyn8, we're working on it!

**Comment by ronaldbarendse** [comment]
Hi @mistyn8, thanks for reporting this! I can confirm the reCAPTCHA v3 field does indeed only show the configured error message to a user/visitor when the score doesn't meet the threshold. All other errors (like a missing or invalid response) will show 'not so friendly' hard-coded messages and they're all logged within Umbraco as warnings too 😞

We'll fix this in a next patch release, so that:
- Any error will show the configured error message to the user/visitor (or fall-back to a generic friendly one if left empty);
- Only configuration issues are logged as warnings (like a missing secret key, as that's something to take action on);
- Log information messages whenever the response field is missing (e.g. removed/not filled in by a bot), invalid or the score did not meet the threshold, so you're able to debug why the reCAPTCHA validation actually failed.
