### ISSUE TITLE
Datasource - Webservice

### ISSUE THREAD

**Issue by Sven883** [umbraco/Umbraco.Forms.Issues#591]
Hello, 

Is it possible to use for example this API https://restcountries.eu/#api-endpoints-all
to populate a dropdown list in a Umbraco forms form?

I would like to fill in a custom datasource but I always get this error:
'Datasource failed to save: Data at the root level is invalid. Line 1, position 1.'
![image](https://user-images.githubusercontent.com/77729251/122023062-7a5c7e00-cdc7-11eb-801b-251f8930afbc.png)

Any ideas ? Thanks!

**Comment by AndyButland** [comment]
The datasource you are looking to create as a web service requires a SOAP service, which you aren't using, so that's why you are getting the error message.

To do what you are looking for though - i.e. create a drop-down list - you should be looking at creating a custom prevalue source type.  There's some documentation that should help you get started on that [here](https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Extending/).

Or - given this data is presumably fairly static - you could just save them into a text file and use the built-in prevalue source type that gets it's values from a text file.
