### ISSUE TITLE
Form submission fails when the view hosting the form is not an Umbraco template

### ISSUE THREAD

**Issue by meyntony** [umbraco/Umbraco.Forms.Issues#606]
A brief description of the issue goes here.

If a DocumentType is rendered without a template, by just using a RenderMvcController and if the View used contains an Umbraco form, the form submission fails with a YSOD:

![image](https://user-images.githubusercontent.com/85172999/124893409-fe76df80-dfda-11eb-80d3-0aa7fcc7e1a8.png)

Reproduction
------------

1. Create a DocumentType eg: NewsPage (without a template)
2. Create a RenderMvcController for the DocumentType eg:  `public class NewsPageController : RenderMvcController`
3. in your Views folder, create a new folder eg: for this example 'NewsPage' inside this folder create a file named 'Index.cshtml'
4. Render an Umbraco form in the above 'Index.cshtml'
Example code: assuming that NewsPage has a property called PickedForm, which is a FormPicker dataType 

`@inherits Umbraco.Web.Mvc.UmbracoViewPage<Umbraco.Web.PublishedModels.NewsPage>`
`@{
    Html.RenderAction("RenderForm", "UmbracoForms", new { formId = Guid.Parse(Model.PickedForm.ToString()), recordId = Guid.Empty, theme = "Bulma", includeScripts = 0 });
}`

Now create content for the above DocumentType, and pick an Umbraco Form, it should render fine, but on form submission give an error like in the screenshot above.

### Specifics

A work around is the create the View being used as a Template.

### Steps to reproduce

Use the attached Umbraco project to see the error after you try to submit the form.
![Capture](https://user-images.githubusercontent.com/85172999/124896702-f7050580-dfdd-11eb-88db-ded4eaae8633.PNG)

### Expected result

Form submission success page

### Actual result

YSOD (screenshot above)

**Comment by AndyButland** [comment]
Have had a look at this.  It seems the limitation here may be in CMS rather than Forms, as what's going wrong here is when Forms is finished with handle the form submission, it calls `CurrentUmbracoPage` to return to the current page and display the "Thanks" message.

And seems you get this error if you are attempting to do this to a route hijacked page.

I've found a couple of ways around it though.

One might be just to use the other option when handling a submitted form, and redirect to a page instead.  That should work as it will do a redirect to a new page and avoid this issue.

The other - via some inspiration from [this blog post](https://lukealderton.com/blog/posts/2016/february/using-umbraco-route-hijacking-and-posting-to-it/) and some work I've done with Umbraco in the past - is to extend your custom route hijacking controller to also be a `SurfaceController` as well, which are designed to accept form posts.

Of course you can't inherit from `SurfaceController` and `RenderMvcController`, but you can inherit from the former and implement `IRenderMvcController`.  And if you do that you can add some code to check the correct location when handling the form post.

Something like this looks to work (by document type here is called "Route Hijacked Page" leading to a view stored in `Views\RouteHijackedPage\Index.cshtml`:

```
using System;
using System.Web.Mvc;
using Umbraco.Web.Models;
using Umbraco.Web.Mvc;

namespace Umbraco.Forms.Testsite.Controllers
{
    public class RouteHijackedPageController : SurfaceController, IRenderMvcController
    {
        public virtual ActionResult Index(ContentModel model) => CurrentTemplate(model);

        private ActionResult CurrentTemplate(ContentModel model)
        {
            var template = ControllerContext.RouteData.Values["action"].ToString();
            if (TryEnsurePhysicalViewExists(template, out string ensuredTemplate) == false)
            {
                throw new Exception($"No physical template file was found for template {template}.");
            }

            return View(ensuredTemplate, model);
        }

        private bool TryEnsurePhysicalViewExists(string template, out string ensuredTemplate)
        {
            // Try to find the view file using the provided template.  When rendering the page with a form
            // this will work and we'll find the view in the default locations searched.
            ViewEngineResult result = ViewEngines.Engines.FindView(ControllerContext, template, null);
            if (result.View != null)
            {
                ensuredTemplate = template;
                return true;
            }

            // If we don't find the view, it means we're in a CurrentUmbracoPage() call following the form submission,
            // so we adjust the provided template location to the folder where it's found, check again, and make sure
            // to use the folder prefixed path when rendering the view.
            ensuredTemplate = "RouteHijackedPage/" + template;
            result = ViewEngines.Engines.FindView(ControllerContext, ensuredTemplate, null);
            return result.View != null;
        }
    }
}
```

**Comment by meyntony** [comment]
Hi @AndyButland,

Thanks for the possible solutions.

Another solution was to create the templates in Umbraco, that solved it too :)

btw do you think an issue for this should be created for the CMS team, since this is not really a Forms issue?

**Comment by AndyButland** [comment]
Perhaps, but it maybe just how this is intended to work - surface controllers for form posts and rendering controllers for page display.  And if you want to do both, then a solution like what I've posted is needed.
