### ISSUE TITLE
Possibility to inject MembershipHelper in fieldtypes and workflows

### ISSUE THREAD

**Issue by inetzo** [umbraco/Umbraco.Forms.Issues#619]
Currently we use Current.UmbracoHelper.MembershipHelper to get the membershiphelper available in fieldtypes and workflows.
While this works, it gives obselete warnings that the membershiphelper should be injected via DI.
But when I try this, Lightning Inject throws errors during the boot.

**Comment by AndyButland** [comment]
Have tried this myself, and see the same.  I'm not 100% sure why, but I expect it's related to [this issue](https://github.com/umbraco/Umbraco-CMS/issues/6335), and how these collections of providers are built up during start-up.

I'm going to close this though as I don't think we can really justify attempting to resolve.  You can safely continue to use `Current.UmbracoHelper.MembershipHelper` even though it's obsoleted, as it won't be removed an any V8 release of CMS or Forms.  And in V9, the `MembershipHelper` no longer exists.

Depending on what you are looking to do with membership helper, you may also be able to work with the particular service that it depends on  - e.g. `IMemberService`.

Or finally, there is this work-around, using lazy injection which defers creation until after start-up and the necessary dependency that otherwise leads to the start-up error is in place:

```
   public class MyWorkflow : WorkflowType
    {
        private readonly Lazy<MembershipHelper> _membershipHelper;

        public MyWorkflow(Lazy<MembershipHelper> membershipHelper)
        {
            _membershipHelper = membershipHelper;
            ...
        }

        ...
        
        public override WorkflowExecutionStatus Execute(Record record, RecordEventArgs e)
        {
            MembershipHelper membershipHelper = _membershipHelper.Value;
            
            // Use the membership helper, e.g.:
            var currentUserName = membershipHelper.CurrentUserName;
            ...
        }
    }
```
