### ISSUE TITLE
Conditional fields not working (Cause found and I have a succinct fix)

### ISSUE THREAD

**Issue by RSDevelopsUK** [umbraco/Umbraco.Forms.Issues#621]
**Problem**

I have set a rule for a text field to show conditionally when a dropdown value of 'Other' has been selected. However when this Other value is chosen, the text box field is not shown.

**Expected result**

The short answer field with the condition set correctly should show when the drop down has the Other value selected.

**Actual result**

The short answer field does not appear.

**Reproduction**

Create a simple form with the following fields:/values
  Dropdown:
      Value 1
      Other
  Short answer:
      Conditions: Show this field if All of the following match: Dropdown is Other

Render the form and select Other: the Short answer field will not show.

**Specifics**

I am using forms version 8.7.6
I am using the Chrome (V 92.0.4515.131)
This issue can be replicated in Internet Explorer (V 20H2 19042.844)
This issue can be replicated in Edge (V 92.0.902.67)
I have found that this issue is **not present** in Firefox (V 90.0.2)

**Proposed fix**

Having followed the umbracoforms.js I actually came across the cause of the issue and have a proposed succinct fix for it.
It revolves around line 263 of the umbracoforms.js:

`formValues[field.getAttribute("id")] = field.value ? field.querySelector("option[value='" + field.value.replace(/'/g, "\\'") + "']").innerText: null;`

What I found was that the above code was transforming the value of Other to

"/n
              Other
/n"

Which was obviously causing the rule check to fail as the above transformed value did not equal Other.

A small fix that I have implemented is to that line as follows:

`formValues[field.getAttribute("id")] = field.value ? field.querySelector("option[value='" + field.value.replace(/'/g, "\\'") + "']").innerText.replace(/\s/g, '') : null;`

By simply adding **.replace(/\s/g, '')** to the innerText method the value does not become transformed and the rule works as expected.

**Comment by AndyButland** [comment]
Thanks for reporting this @RSDevelopsUK - I'm finding though I'm not able to replicate this checking against the latest code.  Would you mind sharing your `FieldType.DropDownList.cshtml` file (found in `Views\Partials\Forms\Themes\default\Fieldtypes\` if you are using the default theme) file please?  As it may be the problem is there, in that you have an old or modified version of that which is introducing these line-breaks within the `value` attribute of the select list's options.

With regard your fix, I think it may also be replacing spaces, which likely isn't what you want (e.g. if you were adding the condition on your "Value 1" value).

**Comment by RSDevelopsUK** [comment]
Hi Andy, Thanks for that you make a good point about the fix. We were using a custom theme and had yet to upgrade the dropdown markup which has fixed our issue. Thanks again!
