### ISSUE TITLE
grecaptcha.ready fails

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#634]
On a Umbraco Cloud project I noticed the forms submit button is now disabled.
I had a look and noticed the `window.grecaptcha.ready` method fails.

![image](https://user-images.githubusercontent.com/2919859/130948960-f3e6d2af-ebd2-4f42-a998-074be1584488.png)

I wonder if something specific has changed regarding this in the recent patch updates? Current on Umbraco Forms v8.7.6

**Comment by bjarnef** [comment]
@AndyButland do you know why that has changed? Is it something in Umbraco Forms or Umbraco core?

I have used this format in several Umbraco v8 project without the need to set `ExcludeScripts`.

```
@Umbraco.RenderMacro("RenderUmbracoForm", new { FormGuid = formGuid, FormTheme = "standard" })
```

What has changed since we need this now?

```
@Umbraco.RenderMacro("RenderUmbracoForm", new { FormGuid = formGuid, FormTheme = "standard", ExcludeScripts = "0" })
```

From what I can tell it is either a patch update of Umbraco or Umbraco Forms that has changed, since I first noticed the issue on this project, when I needed to work on further development. Meanwhile only Umbraco / Umbraco Forms patch updates has changed.

**Comment by c9mbundy** [comment]
@bjarnef - I could be wrong, but I believe that the issue is perhaps in InsertUmbracoFormWithTheme.cshtml which is responsible for creating the action request:
`Html.RenderAction("RenderForm", "UmbracoForms", new {formId = form, recordId = recordGuid, theme = theme, includeScripts = includeScripts });`

**Comment by AndyButland** [comment]
Have had a little dig into this - with the latest Forms and recent CMS it does seem that the `ExcludeScripts = "0"` is necessary.

I _think_ it's due to a change in CMS behaviour.  Looking back over the history there's been a fair bit of change in the rendering macros code, so I haven't been able to pinpoint the actual commit, but it looks to be somewhere in how the `MacroModel` in constructed.

In forms, if you check in `InsertUmbracoFormWithTheme.cshtml`, you'll see we default to including scripts as you expected, but then have this code.  Effectively saying _if an ExcludeScripts parameter is provided, only include the scripts if we've specifically said to not exclude them_.


```
    if (Model.MacroParameters.ContainsKey("ExcludeScripts"))
    {

        @*
            Inverse the boolean - RenderAction Parameter expects it to be false for exclusion
            But with default value for Macro Paramater boolean/checkbox being false 
            We want to ensure by default we include the scripts next to the form
        *@
        includeScripts = Model.MacroParameters["ExcludeScripts"].ToString() == "0";
    }
```

The thing is, even if you don't specifiy the `ExcludeScripts` as in your first example above, it's still provided as a macro paramter.  So the key exists, and the value is empty string, not "0", and hence `includeScripts` is set to false.

I've checked back to 8.0 of Forms and this code snippet hasn't changed.

It's also evidence that we have these `ContainsKey` checks, as with the current CMS versions they don't appear to be necessry.  They key is always provided if it's defined on the macro, even if we haven't provided it in the calling code.  I presume though they once were necessary, and led to the behaviour you originally expected.

I'll check this over for V9 to see if we can change this to no longer do the `ContainsKey` checks if they aren't necessary, and just look at the values, and provide the sensible default of including the scripts.  But I think for V8 we will need to leave as is due to risk of breaking behaviour in the other direction that others are expecting.

**Comment by bjarnef** [comment]
@AndyButland I noticed it is enough with one form on page with `ExcludeScripts = "0"` while the rest can just omit setting this in `Umbraco.RenderMacro()`.

I searched changed since I previous upgraded the site to v8.14.0, but didn't find something specific in the following patch releases.

**Comment by AndyButland** [comment]
Yes, that's expected.  There's a check in the rendering of the scripts to ensure it's only rendered once per page, even if there's more than one form.

**Comment by viliuscicenas** [comment]
In UmbracoForms 7.5.9 issue still persists with both  ExcludeScripts values

**Comment by c9mb** [comment]
@viliuscicenas FWIW - running 7.5.9 on multiple sites without this issue.
