### ISSUE TITLE
UF-7.5.4 reCAPTCHA-v3 - logging response missing/empty

### ISSUE THREAD

**Issue by c9mbundy** [umbraco/Umbraco.Forms.Issues#644]
On some sites that are getting hammered by spambots, we are seeing a lot of log messages:

Of course, we are getting a lot of the expected messages logged:

`INFO "The Google reCAPTCHA v3 score 0.1 did not meet the user definied threshold of 0.5 for the field reCAPTCHA on {{the-form-name}}" `

However, we are also getting a lot of unexpected messages logged:

`INFO "The 'g-recaptcha-response' hidden field for reCAPTCHA v3 is missing/empty and thus unable to be verified"`

I have searched to find where this is being generated or coming from, and can't uncover anything, so I am unable to identify the cause of the issue, or if it's even something I need to deal with.

Given that the script in the reCAPCTHA-v3 field is refreshing the reCAPTCHA client every 60secs, and the reCAPTCHA client has a life-span of 2mins, I would not have anticipated a condition where the hidden field should be empty ?

**Comment by ronaldbarendse** [comment]
The information messages are logged to let you know a form was submitted, but couldn't be verified/validated. You can use this to check why messages might not get submitted...

Actionable issues will be logged as warnings, as described in more detail on https://github.com/umbraco/Umbraco.Forms.Issues/issues/573#issuecomment-845921126.

Both messages indicate the submission came from a bot, although the last one might also be caused by the reCAPTCHA library not loading correctly/not populating the hidden field (which you might want to double-check). In both cases a validation message will be shown to the user (in the validation summary).
