### ISSUE TITLE
Umbraco.RenderMacro outputs 0 after form has been submitted

### ISSUE THREAD

**Issue by GianniDPC** [umbraco/Umbraco.Forms.Issues#679]
If I sumbit a form and want to display the form again using the statement below I get '0' as output. When I refresh the page the form appears like it should.

`Umbraco.RenderMacro("renderUmbracoForm", new { FormGuid = ViewBag.UniqueId, FormTheme = "bootstrap3-horizontal", ExcludeScripts = "0", mode = "form" })`

I'm using Umbraco Forms 8.9.1. FYI: I'm using the old way of storing forms (not storing forms in database)

I did not have this issue using Umbraco Forms 8.7.6 but cannot return to that version because of #632

**Comment by AndyButland** [comment]
I suspect this is coming from the "Message On Submit" you can set when selecting what happens when you submit a form (either display a message, or redirect to a page).  So can you check what you have configured there for the form please?

As to where the "0" comes from, there was a bug fixed in an earlier version where the two options here would get mixed on save, so the unselected redirect page would gets saved to the "message on submit" field with a value of "0".  I can't currently find the link to that issue, but it's certainly fixed by 8.9.1 so if you change this setting to what you want - either a proper message, or a page to redirect to - that should resolve the problem.

**Comment by GianniDPC** [comment]
> I suspect this is coming from the "Message On Submit" you can set when selecting what happens when you submit a form (either display a message, or redirect to a page). So can you check what you have configured there for the form please?
> 
> As to where the "0" comes from, there was a [bug fixed](https://github.com/umbraco/Umbraco.Forms.Issues/issues/502) in an earlier version where the two options here would get mixed on save, so the unselected redirect page would gets saved to the "message on submit" field with a value of "0". This was fixed in 8.7.0, so now you are running on a version after that, if you change this setting to what you want - either a proper message, or a page to redirect to - that should resolve the problem.

I have a page set to redirect after submission. And the message is not shown after submission btw it is shown after requesting the form using Umbraco.RenderMacro so it seems to be some weird bug.

**Comment by AndyButland** [comment]
So just to make sure I understand - you are submitting the form, it successfully redirects to another page, where you render the same form again and see "0" instead of the form open for entry.  Is that correct please?

**Comment by GianniDPC** [comment]
> So just to make sure I understand - you are submitting the form, it successfully redirects to another page, where you render the same form again and see "0" instead of the form open for entry. Is that correct please?


No I store the unique id of the form in a database and request the form again from another page. So the form is rendered within a webpage hence the use of RenderMacro.

I do now see I indeed get the submit message I removed the zero and now the default "Thank you" is back. So it seems the submit message displays on requesting the form instead of on submission.

**Comment by AndyButland** [comment]
I think then if you try clearing `TempData["UmbracoFormSubmitted"]` - i.e. set it to `null` - you should get the behaviour you are looking for.  I believe what's happening is in that the page request following a form submission Umbraco Forms will set this key, and so when a form is being rendered, if it's the same one that's just been submitted the behaviour is to display the "Thank you" message (or whatever is configured).

If you don't want this, then clearing this key should prevent that happening, and render the form for entry.  `TempData` only lasts for one page cycle, so that's why refreshing the page renders the form for entry.

**Comment by GianniDPC** [comment]
> 

Yes that was indeed the issue. Now it works as expected. I have another rather unrelated question within FieldType.FileUpload.cshtml

to retrieve the fileName filePath.Split("/") was used but in newer releases that changed to filePath.Split(new[] { FileUpload.EncryptedFilePathAndFileNameSeparator }, StringSplitOptions.None). My problem is that I can't retrieve the url to file now (because it is encrypted?). So I actually need the fileName AND the filePath

**Comment by AndyButland** [comment]
That's right, with a more recent update we've now encrypted the path to the file as a security precaution as per [this advisory](https://umbraco.com/blog/security-advisory-security-patches-for-umbraco-forms-ready-on-july-20th-2021-at-7-am-utc/).  We don't want to make this path potentially available to website visitors.  You can use the extension method available from Umbraco Core `DecryptWithMachineKey()` to decrypt the file path, but please consider carefully before you do and expose that, as it could open up a security vulnerability.

I'll close of this issue now given we've got a solution for the original request.

**Comment by GianniDPC** [comment]
> That's right, with a more recent update we've now encrypted the path to the file as a security precaution as per [this advisory](https://umbraco.com/blog/security-advisory-security-patches-for-umbraco-forms-ready-on-july-20th-2021-at-7-am-utc/). We don't want to make this path potentially available to website visitors. You can use the extension method available from Umbraco Core `DecryptWithMachineKey()` to decrypt the file path, but please consider carefully before you do and expose that, as it could open up a security vulnerability.
> 
> I'll close of this issue now given we've got a solution for the original request.

Thanks for your help!
