### ISSUE TITLE
Missing option to save all uploaded files to a single zip file

### ISSUE THREAD

**Issue by teeto** [umbraco/Umbraco.Forms.Issues#683]
We are using Umbraco Forms 7.5.4 in a Umbraco v7.15.4 On forms created with previous versions we have an option when exporting to save all uploaded files as a single zip file, but on newer forms that option is not available. Why is this? do we have to enable something on the new forms?

**Comment by AndyButland** [comment]
That option should exist - it certainly does in V8 so I'd expect if you have it available from previous versions it should still be there for the one you are on.  It is the case that the option only shows though if you a) have at least one upload field on your form and b) have had at least one file uploaded for the form.  So could it be you are missing seeing the option because of that?

**Comment by teeto** [comment]
Hi @AndyButland  the thing is that if you export to excel you can see the path of the files attached to the file upload field. 
So i guess it might be an issue with the front detecting the values and showing the option?

**Comment by teeto** [comment]
@AndyButland  could i send you the form so you can test it?

**Comment by AndyButland** [comment]
Sure, that'll help trying to replicate the issue.  I'm _abl AT umbraco DOT dk_.

**Comment by teeto** [comment]
Thanks @AndyButland , i have just sent the form to your email

**Comment by AndyButland** [comment]
Thanks @teeto - I've checked, and I can replicate now what you are seeing.  The export option isn't appearing.

Having had a look it seems that at some point during the evolution of Forms V7, an extra folder was introduced in the path to uploaded files when saved into the media folder, and that wasn't being considered in the check for whether files exist.

I suspect your older forms still had the older directory structure, so that's why they worked as expected.

I'll email you a dll if that's OK that you can try in your installation to see if that solves the problem for you - and if so, will get out in the next official patch release.

**Comment by teeto** [comment]
Sorry i forgot to comment we have installed this package:
https://our.umbraco.com/packages/backoffice-extensions/umbraco-forms-on-perplex-steroids/
So it let us create folders, and that my be the issue.
If you could send me a dll to fix that it would be great.
It will be included also in future updates? i guess other users may have the issue too

**Comment by AndyButland** [comment]
Fix has been prepared and confirm and will come in 7.5.6,
