### ISSUE TITLE
Since the 8.10.x update forms in the backoffice take a long time to load

### ISSUE THREAD

**Issue by Wolfkhan66** [umbraco/Umbraco.Forms.Issues#708]
Users are presented with a gray screen while it loads and it takes so long users tend to think its broken.

Looking into the network tab in the browser the call 'GetByUserID=#' seems to be the culprit and is taking a long time to respond halting the form from loading.

**Comment by AndyButland** [comment]
We weren't able to replicate this issue when reported at the time, and obviously since reporting there's been quite some time for others to report similar issues, which we haven't seen.  We'll likely close as non-reproducible but if you are still seeing the issue and can let us know a bit more detail about the timings you are seeing and effect it is having, please let us know and we'll investigate further.
