### ISSUE TITLE
Disapprove workflows

### ISSUE THREAD

**Issue by inetzo** [umbraco/Umbraco.Forms.Issues#716]
We use Umbraco Forms for an Intranet environment. One of the things it is used for is to approve applications-forms for public transport. A Member submits a request and a User must approve it. However, there are situations where an application-form cannot be approved, for example because the form has not been completed correctly or because something is missing. In that case, it would be very nice if an OnDisapprove workflow could be set up the same way as an OnSubmit and OnApprove workflow. 

---
_This item has been added to our backlog AB#33998_

**Comment by CDSFounder** [comment]
Is it possible to extend this to allow for configurable or extendable form states? We would like to have more states than just Approve, Reject, Submitted. 

As an example: We would like to have a form state "Re-opened" where a form is technically rejected, but the state Re-opened kicks it back to the member's front-end portal with a note for why it was rejected. The member could then see a list of their submitted forms and "continue" the form listed as "Re-opened" along with the note for why it was re-opened and proceed to fix any issues and re-submit the form. This is different than a rejected state because the member would be allowed to resubmit the form with minor corrections, as opposed to simply permanently rejecting what was submitted. 

As another example: In the case of multi-page forms, it would be nice to allow the member to save the form progress and come back to it later. In this case, the form would be in an "In Progress" state. 

@AndyButland  @BoletteKern

**Comment by AndyButland** [comment]
Looks like we should have closed this issue as an "On Reject" workflow has been added to Forms as part of the 12.2 release, and so is available in 13+ too.
