### ISSUE TITLE
Upgrade to 8.8.0 from 8.11.0 Fails.

### ISSUE THREAD

**Issue by uSkinned** [umbraco/Umbraco.Forms.Issues#739]
After upgrading Umbraco Forms via Nuget and then running site get following error:

`System.Data.SqlClient.SqlException: The operation failed because an index or statistics with name 'UK_UFForms_Key' already exists on table 'UFForms'.`

**Comment by AndyButland** [comment]
I'm not initially able to replicate this.  It _looks_ like the migration here should be idempotent, in that it checks for a constraint existing before trying to create one.  Could you let me know a bit more details about your set up please?

- SQL Server or SQL CE?
- Are you storing form definitions in the database or on disk?
- If you changed from storing form definitions on disk to in the database, did you do that whilst running 8.8, or as part of the upgrade to 8.11?

Thanks

**Comment by uSkinned** [comment]
Hi Andy,

- SQL Server
- Form Definitions in database in 8.8 version
- Continue in database with upgrade to 8.11

Let me know if you want me to try again. I have currently rolled back to a DB copy before the upgrade attempt.

**Comment by uSkinned** [comment]
Hi Andy,

Just to confirm, I have tried again and get the same error message.

Cheers,

Marc

**Comment by AndyButland** [comment]
Would you mind sharing with me the results of this query please?

```
SELECT TABLE_NAME,CONSTRAINT_TYPE
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE CONSTRAINT_NAME = 'UK_UFForms_Key'
```

This data is what the migration is checking to see if a constraint exists before creating it, only doing so if it doesn't find one.  I've tried replicating your upgrade path and it seems to work for me as expected, i.e. not trying to recreate a constraint that doesn't exist.  So just wanted to check that this "check" is valid in your database.

**Comment by uSkinned** [comment]
Strange thing is that the index is present if I inspect the DB Indexes. 
![sql-server](https://user-images.githubusercontent.com/22817718/157454932-87027a4a-4b08-4168-a7a5-dc2cf45cac9a.png)

**Comment by AndyButland** [comment]
Interesting... so, I see the same when I inspect the indexes for the table, but I _do_ get a record back from the query.  So that explains to an extent what's going wrong - in your setup the migration is considering that a constraint doesn't exist, it tries to create it, and gets an error as it actually already does.

Leaves the question of why you don't get a record back from that query and I do.  What version of SQL Server are you running please?

---

There's a workaround here that if you remove the constraints before running the migration, that should allow you to complete it - as then it'll be able to create them without issue.  There are four, so I think if you remove these the migration should run.

```
ALTER TABLE dbo.UFForms
DROP CONSTRAINT IF EXISTS UK_UFForms_Key
GO

-- Reverts addition of unique constraint to UFPrevalueSource.
ALTER TABLE dbo.UFDataSource
DROP CONSTRAINT IF EXISTS UK_UFDataSource_Key
GO

-- Reverts addition of unique constraint to UFPrevalueSource.
ALTER TABLE dbo.UFPrevalueSource
DROP CONSTRAINT IF EXISTS UK_UFPrevalueSource_Key
GO

-- Reverts addition of unique constraint to UFWorkflows.
ALTER TABLE dbo.UFWorkflows
DROP CONSTRAINT IF EXISTS UK_UFWorkflows_Key
GO
```

**Comment by uSkinned** [comment]
Hi Andy,

Great, will remove indexes and try again. Using SQL Server 2019. Yes, very strange that your query does not return any results.

Cheers,

Marc

**Comment by uSkinned** [comment]
Interesting Issue, your drop commands didnt remove the indexes. Will manually remove them and let you know if upgrade works.

**Comment by uSkinned** [comment]
Hi Andy,

Upgrade worked this time and all the indexes are back in place. I guess my issue is with SQL Server then and why the indexes aren't found with a query.

Thanks for your help. At least I can now run 8.11.0.

Cheers,

Marc

**Comment by AndyButland** [comment]
That's good then, but still a bit concerned to have not found the reason.  I'm also testing with SQL 2019, so it doesn't seem to be version specific.

> your drop commands didn't remove the indexes

That must be related to the problem.  As they do on my installation, I assume for the same reason, whatever it is.

**Comment by uSkinned** [comment]
Would it help if I send you a backup copy of my database? I can PM you via twitter for details?

**Comment by AndyButland** [comment]
Might be worth a look if you didn't mind.  Thanks if so - would be good to try further to get to the bottom of it.

**Comment by uSkinned** [comment]
Just followed you on Twitter, can you follow me back so that I can send you a message?

**Comment by AndyButland** [comment]
OK, so I see this difference if I generate a create script for the two constraints.

In my database I get:

```
ALTER TABLE [dbo].[UFForms] ADD  CONSTRAINT [UK_UFForms_Key] UNIQUE NONCLUSTERED 
(
	[Key] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
```

And in yours:

```
CREATE UNIQUE NONCLUSTERED INDEX [UK_UFForms_Key] ON [dbo].[UFForms]
(
	[Key] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
```

I.e. a _unique constraint_ versus a _unique index_.

So that explains a bit more why the migration fails... it's looking specifically for a constraint rather than an index, doesn't find it so tries to create it.  But it then errors as an index with that name already exists.

The question remains though why our databases are different.  The migration code relies on Umbraco to create the constraints, and as far as I can see that uses, and has always for V8 used, the version from my database.

Probably worth asking if you or a colleague may have manually created this index previously?  Seems unlikely as the odds of you picking the same name would be slim, but worth checking.

Would also be interesting to know if, now you have done the migration, what version you have now.  I.e. script the constraint from management studio and see which of the two versions above you get.  And/or run this query again and see if you now have a record:

```
SELECT TABLE_NAME,CONSTRAINT_TYPE
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE CONSTRAINT_NAME = 'UK_UFForms_Key'
```

Thanks again for the help with diagnosing this.

**Comment by uSkinned** [comment]
Hi Andy,

I now get the index running the select query. I am the only person that has worked directly on this database so no one would have manually created this index. 

I can tell you that this database was setup initially with Umbraco 8.12.1 and Umbraco Forms 8.6.1

Cheers,

Marc

**Comment by AndyButland** [comment]
OK, at least that means you should be fine going forward.  My only theory is that as per Umbraco 8.12 (or whatever version you were on when you first migrated to or beyond 8.7) is that Umbraco was creating these unique constraints as indexes rather than as constraints as it does now.  Looking back through the code history I can't see evidence of that though.

Anyway, at least now you have the unique constraint set up, you'll be fine going forward.

And sounds like I should extend the check we currently have to look for an existing unique constraint _or an index_ with the name before attempting to create a unique constraint.

**Comment by uSkinned** [comment]
Okay great and thanks for your help on this.
