### ISSUE TITLE
7.0.6: Having more than one date picker overrides the entries

### ISSUE THREAD

**Issue by jmayntzhusen** [umbraco/Umbraco.Forms.Issues#74]
Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

When you have a form with more than one date picker, the entries will only list the last one.

### Specifics

Using Forms v7.0.6, it has been reported to be working fine on 7.0.5 but not 7.0.6. Have only checked in Chrome

### Steps to reproduce

1. Create a Form with two date pickers
1. Pick it in a RTE on a content node
1. Go to the frontend and put in two dates, then submit
1. The entries only list a date for the last date picker

### Expected result

Both entries should be there

### Actual result

Only the last one was there

**Comment by ThoughtProcess** [comment]
I'll add a quick comment here for folks who need a workaround until 7.next gets released.

The bug appears to come from this block in `datepicker.init.js`:

```
var datePickerFields = document.getElementsByClassName('datepickerfield');
for (var i = 0; i < datePickerFields.length; i++) {
    var field = datePickerFields[i];
    var currentId = field.id;
    new Pikaday({
        field: document.getElementById(currentId),
        yearRange: e.umbracoFormsLocale.datePickerYearRange,
        i18n: e.umbracoFormsLocale.locales,
        format: "LL",
        onSelect: function (date) {
            setShadow(currentId.replace("_1", ""), date);
        },
        minDate: new Date('1753-01-01T00:00:00') //Min value of datetime in SQL Server CE
    });
}
```

The problem lies in the declaration of `var currentId` inside the for-loop.  JavaScript doesn't have block-level scope like other curly-braced languages.  That means that the `currentId` referenced in the `onSelect` callback closure points to the _same_ variable through each iteration of the loop, leading to the behavior that @jmayntzhusen described.

A temporary workaround that I used successfully was to swap the `for(...)` with `Array.prototype.forEach()`, as shown below:

```
var datePickerFields = document.getElementsByClassName('datepickerfield');
Array.prototype.forEach.call(datePickerFields, function(field) {
    var currentId = field.id;
    new Pikaday({
        field: document.getElementById(currentId),
        yearRange: e.umbracoFormsLocale.datePickerYearRange,
        i18n: e.umbracoFormsLocale.locales,
        format: "LL",
        onSelect: function (date) {
            setShadow(currentId.replace("_1", ""), date);
        },
        minDate: new Date('1753-01-01T00:00:00') //Min value of datetime in SQL Server CE
    });
})
```

A bit of further reading can be found here:  https://stackoverflow.com/questions/750486/javascript-closure-inside-loops-simple-practical-example
