### ISSUE TITLE
Upload field doesn't allow any file types after upgrading

### ISSUE THREAD

**Issue by Jeavon** [umbraco/Umbraco.Forms.Issues#742]
After upgrading forms from 8.6.2 to 8.11.0 the upload fields on forms prevent any types from being accepted.
When checking the back office form editor there are no allowed types showing and when attempting to toggle the all option a JS error is thrown as shown.

The workaround is to delete the field and recreate it.

![image](https://user-images.githubusercontent.com/1829920/157641437-52e6d803-864e-4fd0-bf60-d8516b3a1587.png)

**Comment by AndyButland** [comment]
Thanks for the report @Jeavon.  I've tried to replicate this today by following that upgrade path - i,e, a fresh install of 8.6, create a form with upload fields with different combinations of allowed types, and upgrade to 8.11 - but haven't been able to find this issue.

Are you still in a position to share the form definition from the database or file from before you recreated the field please?  Don't worry if not, but if so that might allow me to create it behind the scenes in an 8.11 and debug the issue a bit more.

**Comment by AndyButland** [comment]
Will close this one now - as haven't been able to replicate or have had any further reports, and there appears to be a workaround.
