### ISSUE TITLE
Long description in custom export provider causes layout to break

### ISSUE THREAD

**Issue by aguyfromdenmark** [umbraco/Umbraco.Forms.Issues#839]
If the description of a custom export provider is really long, the layout will break. 

![image](https://user-images.githubusercontent.com/6904597/183863333-d6f8b030-7534-46f4-9fba-b45298761bf8.png)

Reproduction
------------

### Specifics

This is on Forms v. 9.4.1 and I have tested it in Firefox and Chrome. 

### Steps to reproduce

Create a custom export provider and give it a really long description.

### Expected result

Layout should look good.

### Actual result

The layout does not look good.

**Comment by AndyButland** [comment]
I believe this has been fixed in a later version than you are running.  We came across the same issue when introducing a second Excel export option, and requiring a longer description.  From 8.13/9.5/10.1 you should see it looks like this:

![image](https://user-images.githubusercontent.com/1993459/184622033-d7134b45-279c-4b8f-9978-620a8566adb7.png)
