### ISSUE TITLE
Ability to add a label and key to all Answer Type prevalues

### ISSUE THREAD

**Issue by Ultradata-CXP** [umbraco/Umbraco.Forms.Issues#84]
**Issue**

We have a number of prevalues that need to be displayed to the form applicant in a human readable form but stored and interpeted by form processors and APIs as a different value.

**Required**

Please allow form editors to add a label and key against all answer type prevalues.

**Comment by nul800sebastiaan** [comment]
Thanks for your feature request! We don't immediately have plans to implement this feature. I've put it on the ideas list however for when we revisit prevalues and field configurations.

For now we'd encourage you to look into custom workflows that can transform the data before it's being submitted to the form processors/APIs.

https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Extending/Adding-a-Workflowtype

**Comment by martijnbeumers** [comment]
Hi, I really encourage Umbraco HQ to make this feature a priority. This is a must-have for any modern Form generator tool. I was a bit suprised that this is still not possible. For database prevalues it is already posible. So why not the rest of the options?

Custom workflows is not a viable option. Than an Editor need to maintain lists on two separate places. 

Can you bump this one up on the list @nul800sebastiaan ?

**Comment by martijnbeumers** [comment]
![image](https://user-images.githubusercontent.com/30809240/102343298-a58e1e00-3f9a-11eb-8a74-4d909148d97e.png)

**Comment by martijnbeumers** [comment]
Like this:
![image](https://user-images.githubusercontent.com/30809240/102343350-b6d72a80-3f9a-11eb-821d-f20ba895502f.png)

**Comment by hfloyd** [comment]
Yes, this is a must. 

I can understand that for certain sources this wouldn't work (for existing DataTypes which have prevalues stored as essentially a single text value each), but I think for the text file option, accepting a "CSV" would take care of this easily (there can still be a fallback for "single column" files to use the data as both the value and the caption. For the "Use Umbraco nodes" type, the addition of two extra properties would be perfect: the "Caption" property and the "Value" property - which would be property alias drop-downs (plus "node name" option).

It seems that the main consideration is the addition of a new property to the "Prevalue" model - of "Caption" or "Display Text" - but this doesn't feel like a breaking change to me, since missing caption data can easily fallback to returning the Value data for that property.

**Comment by AndyButland** [comment]
Prevalues with captions and values will be available from the next minor release.

**Comment by hfloyd** [comment]
@AndyButland I'm working on a Docs PR related to this, and was looking for a pre-release version of 9.5.0 in order to check the name of the new "caption" property, but couldn't find any available in NuGet or nightlies... So can you confirm - the name of the new property will be ".Caption"?

**Comment by AndyButland** [comment]
Yes, that's right.  I've got a docs PR pending for all of the features coming in the next minor, which is [here](https://github.com/umbraco/UmbracoDocs/pull/3937).  If it's useful, I've also shared with you a work in progress blog post for the RC release, so you can see there what I've written about this feature.

**Comment by hfloyd** [comment]
Well, I finally got around to looking at the Doc I was preparing, and saw that you added the file with your commit. So, I just updated it with a few things I had included in mine. https://github.com/umbraco/UmbracoDocs/pull/4553
