### ISSUE TITLE
Magic string not working in  "Field mandatory message" for property of type Data Consent

### ISSUE THREAD

**Issue by Seda145** [umbraco/Umbraco.Forms.Issues#868]
Steps:
Umbraco: 10.1.0
Forms: 10.1.0

1. Create a form with a field of type Data Consent.
2. Below the "Field is mandatory" button enter a dictionary reference (prefixed #) as mandatory message.
3. Attempt to submit the form on the website without filling in the field.
4. See how the mandatory message will not be translated and will instead print the dictionary key.

![afbeelding](https://user-images.githubusercontent.com/30213433/190003546-c5d232db-f683-4ec7-adea-183529eee48b.png)

---
_This item has been added to our backlog AB#41044_

**Comment by AndyButland** [comment]
Hi - I've been investigating this, but I haven't been able to replicate the issue (at least with the latest code, Forms 10.1.2, but I don't think anything has changed in this area since the version you are running.

I guess I should ask if you could to double-check please that the dictionary key you have set up in the _Translation_ section is exactly `Form.Validation.ConsentIsRequired`?

**Comment by Seda145** [comment]
Hello Andy,

I have double checked it using another dictionary item which works on another field but not the mandatory message field of the data consent property.
I have cleared all caches and restarted the application as well.
________________________________
Van: Andy Butland ***@***.***>
Verzonden: woensdag 14 september 2022 08:00
Aan: umbraco/Umbraco.Forms.Issues ***@***.***>
CC: Roy Wierer ***@***.***>; Author ***@***.***>
Onderwerp: Re: [umbraco/Umbraco.Forms.Issues] Magic string not working in "Field mandatory message" for property of type Data Consent (Issue #868)


Hi - I've been investigating this, but I haven't been able to replicate the issue (at least with the latest code, Forms 10.1.2, but I don't think anything has changed in this area since the version you are running.

I guess I should ask if you could to double-check please that the dictionary key you have set up in the Translation section is exactly Form.Validation.ConsentIsRequired?

**Comment by Ramya-Devendiran** [comment]
I face same issue in Umbraco forms 12.2.3. Is this issue fixed?
[UmbracoForms12_ConsentMessageTranslation.docx](https://github.com/umbraco/Umbraco.Forms.Issues/files/15400769/UmbracoForms12_ConsentMessageTranslation.docx)

**Comment by AndyButland** [comment]
We've had another look at trying to replicate this one, across the latest on Forms 10, 12 and 13, but are not able to I'm afraid.

The only way we could see it is if the required `@Html.RenderUmbracoFormDependencies()` isn't provided on the template, so perhaps that's the case with your situation.

I can [share the replication](https://drive.google.com/file/d/12C9QVb_pKUacYsa3x4zwpWekUG1lXPUl/view?usp=drive_link) I did just in case it shows something that's different for your case.

But otherwise as we can't see this in the latest versions of each major, will close now as non-reproducible.

**Comment by AndyButland** [comment]
Perhaps you can share the error you are seeing?
