### ISSUE TITLE
Textarea value not submitted/emtpy when the field has conditions

### ISSUE THREAD

**Issue by mcl-sz** [umbraco/Umbraco.Forms.Issues#881]
When a form has a textarea (Long answer) and a condition is added, the value is not saved when submitting the form.

Reproduction
------------

- Install Umbraco Forms 8.13.2 or earlier.
- Create a form with an checkbox (name "Test") and a textarea/long answer (name "Message").
- Add an condition to the textarea:  "Show this question if all of the following match: Test is True"
- Add the form to a page
- Goto to the page, check the checkbox, enter a text in the "Message" field and submit the form.
- Check the form entry in the backoffice: the "Message" field is empty.

### Expected result

I would expect that the "Message" field is saved.

### Actual result

The "Message" field value is not saved.

**Comment by AndyButland** [comment]
Thanks for reporting... I'll close this though as it's already on the radar in [this issue](https://github.com/umbraco/Umbraco.Forms.Issues/issues/875), though admittedly it's not super-clear as there's been a bit of discussion in there.

To summarise, this should work as expected if the value you are testing against is "true" rather than "True".  We're working on a fix for the next patch update to make this case insensitive, so it aligns with the conditional logic used client-side.
