### ISSUE TITLE
Make it possible to upgrade straight from <9.5 to 10

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco.Forms.Issues#892]
When you upgrade Forms from eg. 9.3 to 10.1.2, it breaks. The upgrade instructions tells you to upgrade to the latest 9-minor before upgrading to 10.

Is this because some migrations were removed in 10? I think it would be great if you could go from any 9.x version to 10. Having to do these in-between steps is quite annoying.

https://our.umbraco.com/forum/using-umbraco-and-getting-started/110145-umbraco-forms-9-to-10-upgrade-issues

**Comment by AndyButland** [comment]
It is necessary to go to at least what was the latest minor when Forms 10 came out I'm afraid.  So that's 8.12 or 9.4.

And yes, the reason is the migration steps got cleaned up and combined in Forms 10.  Partly this was just a bit of housekeeping/clean-up, but the main reason was the introduction of SQLite, which meant the existing migration path wouldn't work (due to restrictions around issuing `ALTER TABLE...` statements on SQLite).  Although of course no-one was upgrading from SQLite from Umbraco 9, we still need to use the same set of migration steps for both providers on 10+.

So I don't think we can make this change unfortunately.

At the end of the day though, these migration steps are just SQL updates, and I have started internally collating scripts for making these changes outside of the normal migration flow.  It's not something we want to encourage or officially support, but they have been useful for internal development purposes and occasional support assistance.  So I can share what I have for upgrade from 9.3 if you like and are happy to review carefully before applying... just reach out if that's useful.
