### ISSUE TITLE
Dictionary Items in Rich Text Field Type

### ISSUE THREAD

**Issue by Trobeloo** [umbraco/Umbraco.Forms.Issues#903]
Hello,
We have a multi language site and use Dictionary Items in Forms. In our current Umbraco 8 site we created a custom Field type to display Dictionary Items as Html.
We are converting to Umbraco 10 and latest Forms version. Is it possible to use the new Rich Text Field Type to display Dictionary Items.
I tried to put item tag "#PR License Hint" in the field but it doesn't get replaced by the dictionary item content.

**Comment by AndyButland** [comment]
I just checked this and can confirm it doesn't currently work no.  The reason is that dictionary items are only parsed if they are the only text in the field, which made sense for most other use cases (like captions, default values etc.), where you want to translate the whole text.

For rich text of course there's HTML tags as well, so currently this isn't being recognised as a field containing tags to replace.

Will see if we can add support for this though in an upcoming release.

**Comment by Trobeloo** [comment]
Thanks Andy.
I think I was using the wrong FieldType as the "Title and descrription" field type is doing what I need.
In the Body property I enter a Dictionary Items "#PR License Hint"
In English it contains: 
<p>To learn more about our licensing system, please visit <a data-udi="umb://document/69dad08dea664d1db4200f07ca32840a" href="/{localLink:umb://document/be528bf313d847ae87b6c284acec1234}" title="Sales">this page</a>.</p>

When the form is displayed the Html is correctly rendered.

**Comment by AndyButland** [comment]
Yes, it'll work with "Title and description" as for that one the value isn't stored embedded within one or more an HTML tag.  I've been working on it this morning for rich text too though, and think we can make it work for that field too.

**Comment by AndyButland** [comment]
We'll include replacements of magic strings within HTML tags in the next release.

**Comment by Trobeloo** [comment]
Great
