### ISSUE TITLE
Streamline the selection of file types for file upload field

### ISSUE THREAD

**Issue by karlmacklin** [umbraco/Umbraco.Forms.Issues#939]
This is the current fastest process we have found, to successfully add and designate a custom allowed file type to a file upload field:

1. Enter the file ending under the input field "Add new allowed file type". Hit add. The file ending is now put into a temporary holding space:
![image](https://user-images.githubusercontent.com/353806/207601510-dc7f1696-e8e2-441a-84c7-bfcc4f64c431.png)

2. Submit the field.
3. Save the complete form.
4. Reload your browser.
5. Reopen the file upload field question definition.
6. At this point the file type ending is visible in the list of "Predefined allowed file types", and we can click to add it. And finally save the field, and then the form, to have completed the process.

![image](https://user-images.githubusercontent.com/353806/207602225-be3e94e7-134a-4c7a-9f78-76815abdc1ae.png)

This process is unnecessarily cumbersome and convoluted. Especially step 4 which is not expected by our clients.

This feature request asks to simplify this process somehow. If not in less steps, then at least in more apparent steps for the regular web editor that may always employ the"try every thing you can think of to make it work" as an approach.

**Comment by AndyButland** [comment]
I see and can replicate - but this isn't intentional.  The idea - and behaviour in versions prior to 10.2.0 is that you see something like this (both after adding the new extension, and when you reload the form):

![image](https://user-images.githubusercontent.com/1993459/207650427-cadcf0de-9c9a-4f37-9291-c7e54a961c19.png)

The added extension shouldn't appear in the list of predefined types.

I believe we've inadvertently caused this behaviour in the resolution of [this issue](https://github.com/umbraco/Umbraco.Forms.Issues/issues/916).  The code was otherwise relying on an "undefined" state of the check box for added extension, but now it's being explicitly set to false.

You've found a workaround... but we'll look to get this fixed up and restore the previous behaviour.

**Comment by AndyButland** [comment]
This will be resolved in the next 10+ patch releases.
