### ISSUE TITLE
v11: Custom field type breaks backend

### ISSUE THREAD

**Issue by Nuklon** [umbraco/Umbraco.Forms.Issues#954]
In Umbraco Forms 11, if you have a custom field type that derives from a base type, it breaks the backend in trying to render the main page of the website. I've now named my custom type the same as the built-in type and it renders again correctly.

Reproduction
------------

Create a type such as:
```csharp
public sealed class MaxFileUpload : Umbraco.Forms.Core.Providers.FieldTypes.FileUpload

  public MaxFileUpload
    (
        IOptions<SecuritySettings> config,
        IHostEnvironment hostingEnvironment,
        MediaFileManager mediaFileManager,
        IDataProtectionProvider dataProtectionProvider) :
        base(config, hostingEnvironment, mediaFileManager, dataProtectionProvider)
    {
        Id = new Guid("c87cba1a-b333-43b7-bf75-86610a0d12ad");
        Name = "File upload with file size";
        FieldTypeViewName = "FieldType.MaxFileUpload.cshtml";
    }

// rest doesn't matter.
```

### Specifics

Add above field to a form. Restart app and go to /umbraco/#/forms/Form/edit/whatever-the-id-is
Now open the homepage of your website in a new tab (or refresh it if you already have it opened).
Go back to backend and it renders the website inside the preview of the max file upload field. If it doesn't happen, try refreshing the form edit page. As a workaround I've now named my custom type the same as FileUpload and it renders a file upload preview again. Happens in FF and Chrome.

**Comment by ronaldbarendse** [comment]
Hi @Nuklon! I haven't tried replicating this yet, but going from your example and description, it looks like the design view can't be found and it's returning a custom 404 error page instead.

This is because the default implementation of `GetDesignView()` will try to render `~\App_Plugins\UmbracoForms\backoffice\Common\FieldTypes\maxfileupload.html`, which won't exist, but renaming the field type to `FileUpload` will find the default built-in view again and render correctly. Please check the documentation: https://docs.umbraco.com/umbraco-forms/developer/extending/adding-a-fieldtype#umbraco-backoffice-view.

Adding the following override should fix this issue:
```
public override string GetDesignView() => "~/App_Plugins/UmbracoForms/backoffice/Common/FieldTypes/fileupload.html";
```

Please let me know if this is indeed the case! 😄

**Comment by AndyButland** [comment]
I'll close this one now given a response is provided that sounds like it will resolve the issue.  If not, please feel free to re-open.
