### ISSUE TITLE
Rich Text Url Picker doesn't render link

### ISSUE THREAD

**Issue by OwainWilliams** [umbraco/Umbraco.Forms.Issues#972]
Reproduction
------------

Add a Richtext box in to a form.
![image](https://user-images.githubusercontent.com/9438758/218078708-7ff25859-37db-47a9-a9b1-6f77b23f3f8a.png)

Add a link to an internal page using the Url picker within the toolbar on the RTE.

![image](https://user-images.githubusercontent.com/9438758/218078812-f676e823-1b95-4563-b575-cac7e3a0710a.png)

View the form on the front-end and you will see the url directs to <a href="/"> instead of the page you picked in the backoffice

### Bug summary

After speaking to a few people, it looks like the Property Value Converter isn't parsing the url `<a href="/{localLink:umb://document/87f1f3f61e5c4d879e36c9b15dd90a75}"` for example.

### Specifics

Umbraco : 10.1.1
Forms: 10.2.1

### Expected result

The link should point to the picked destination, not just "/"

**Comment by AndyButland** [comment]
Thanks for the report @OwainWilliams.  I've had a look, and seems like the problem is actually that the syntax for these local links overlaps with what we use in forms for "magic strings" member placeholders.  So we're currently considering it as one of those, not finding a match, and removing it.

I've made a change such that we no longer do that, and then the internal links renders as you'd expect.

I'll mark this to be included in the next patch release, but, depending on timings, it might just get rolled up into the next minor.

**Comment by OwainWilliams** [comment]
Thanks @AndyButland - Is there a way we can temporarily fix this locally?

**Comment by AndyButland** [comment]
I don't think so I'm afraid - it required a server-side change in the implementation of `IPlaceholderParsingService`, so whilst in theory you could swap that out, but in practice there's a a lot of code in there that you won't have/would have to rewrite, so it's not really feasible.

**Comment by OwainWilliams** [comment]
No problem. Thanks for the quick reply Andy. Appreciate it.

**Comment by AdoPasa** [comment]
@OwainWilliams in order to avoid this behavior you can created an RTE question type with disabled placeholder on the html property and use that question type in the form and use it in the same way as the standard RTE question type. (this is just for temporarily  usage)

![image](https://user-images.githubusercontent.com/18100258/218677767-24c2ba54-747c-4592-810a-c34d38d8f881.png)



```
using Umbraco.Forms.Core.Attributes;
using Umbraco.Forms.Core.Enums;
using Umbraco.Forms.Core;

namespace UmbracoProject.Forms.CustomFieldTypes
{
    public class RichTextWithoutPlaceholdersField : FieldType
    {
        public RichTextWithoutPlaceholdersField()
        {
            this.Id = new Guid("1F8D45F8-76E6-4550-A0F5-9637B8454629");
            this.Name = "Rich text without placeholders";
            this.Alias = "richTextWithoutPlaceholders";
            this.Description = "This rich text question type should be used if you want to use internal links. With this question type you are not able to use placeholders (a.k.a magic strings)";
            this.Icon = "icon-code";
            this.DataType = FieldDataType.LongString;
            this.Category = "Simple";
            this.SortOrder = 110;
            this.FieldTypeViewName = "FieldType.RichText.cshtml";
        }

        public override string GetDesignView()
        {
            return "~/App_Plugins/UmbracoForms/backoffice/Common/FieldTypes/richtext.html";
        }


        [Setting("Rich text", Description = "Enter your formatted text", DisplayOrder = 10, SupportsPlaceholders = false, View = "richtext")]
        public string Html { get; set; } = string.Empty;

        [Setting("Show Label", Description = "Indicate whether the the field's label should be shown when rendering the form.", DisplayOrder = 20, PreValues = "false", View = "checkbox")]
        public string ShowLabel { get; set; } = string.Empty;

        public override bool HideLabel => this.ShowLabel != "True";

        public override bool StoresData => false;

        public override bool SupportsMandatory => false;
    }
}
```

**Comment by Deba22** [comment]
Hi @AndyButland @OwainWilliams 

This same issue I can reproduce now in umbraco forms v13.5.0 and Umbraco v13.9.2
Any thoughts on this?
